// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


//======================

void Vtop::trace(VerilatedFstC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vtop::traceInit(void* userp, VerilatedFst* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vtop::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vtop::traceInitTop(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vtop::traceInitSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+1,"CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+2,"RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+3,"input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+7,"input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+11,"input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+15,"input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+19,"input_function_mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+20,"EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+21,"RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+22,"ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+26,"RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+27,"decrypted_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+31,"RDY_decrypted_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+32,"tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+36,"RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+37,"decrypted_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+41,"RDY_decrypted_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+42,"mkAscon_engine CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+43,"mkAscon_engine RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+44,"mkAscon_engine input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+48,"mkAscon_engine input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+52,"mkAscon_engine input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+56,"mkAscon_engine input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+60,"mkAscon_engine input_function_mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+61,"mkAscon_engine EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+62,"mkAscon_engine RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+63,"mkAscon_engine ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+67,"mkAscon_engine RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+68,"mkAscon_engine decrypted_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+72,"mkAscon_engine RDY_decrypted_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+73,"mkAscon_engine tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+77,"mkAscon_engine RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+78,"mkAscon_engine decrypted_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+82,"mkAscon_engine RDY_decrypted_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+83,"mkAscon_engine counter",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBus(c+84,"mkAscon_engine counter_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBit(c+85,"mkAscon_engine counter_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+86,"mkAscon_engine fsm_state",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBus(c+87,"mkAscon_engine fsm_state_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBit(c+88,"mkAscon_engine fsm_state_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+89,"mkAscon_engine iv_constant",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+91,"mkAscon_engine iv_constant_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+93,"mkAscon_engine iv_constant_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+94,"mkAscon_engine ready_ciphertext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+95,"mkAscon_engine ready_ciphertext_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+96,"mkAscon_engine ready_ciphertext_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+97,"mkAscon_engine ready_decrypted_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+98,"mkAscon_engine ready_decrypted_data_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+99,"mkAscon_engine ready_decrypted_data_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+100,"mkAscon_engine ready_decrypted_tag",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+101,"mkAscon_engine ready_decrypted_tag_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+102,"mkAscon_engine ready_decrypted_tag_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+103,"mkAscon_engine ready_tag",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+104,"mkAscon_engine ready_tag_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+105,"mkAscon_engine ready_tag_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+106,"mkAscon_engine req_associated_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+107,"mkAscon_engine req_associated_data_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+108,"mkAscon_engine req_associated_data_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+109,"mkAscon_engine rg_decrypted_data_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+111,"mkAscon_engine rg_decrypted_data_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+113,"mkAscon_engine rg_decrypted_data_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+114,"mkAscon_engine rg_decrypted_data_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+116,"mkAscon_engine rg_decrypted_data_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+118,"mkAscon_engine rg_decrypted_data_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+119,"mkAscon_engine rg_decryption_tag_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+121,"mkAscon_engine rg_decryption_tag_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+123,"mkAscon_engine rg_decryption_tag_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+124,"mkAscon_engine rg_decryption_tag_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+126,"mkAscon_engine rg_decryption_tag_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+128,"mkAscon_engine rg_decryption_tag_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+129,"mkAscon_engine rg_encrypted_data_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+131,"mkAscon_engine rg_encrypted_data_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+133,"mkAscon_engine rg_encrypted_data_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+134,"mkAscon_engine rg_encrypted_data_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+136,"mkAscon_engine rg_encrypted_data_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+138,"mkAscon_engine rg_encrypted_data_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+139,"mkAscon_engine rg_encryption_tag_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+141,"mkAscon_engine rg_encryption_tag_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+143,"mkAscon_engine rg_encryption_tag_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+144,"mkAscon_engine rg_encryption_tag_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+146,"mkAscon_engine rg_encryption_tag_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+148,"mkAscon_engine rg_encryption_tag_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+149,"mkAscon_engine rg_interface_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+153,"mkAscon_engine rg_interface_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+157,"mkAscon_engine rg_interface_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+158,"mkAscon_engine rg_interface_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+162,"mkAscon_engine rg_interface_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+166,"mkAscon_engine rg_interface_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+167,"mkAscon_engine rg_interface_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+171,"mkAscon_engine rg_interface_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+175,"mkAscon_engine rg_interface_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+176,"mkAscon_engine rg_interface_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+180,"mkAscon_engine rg_interface_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+184,"mkAscon_engine rg_interface_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+185,"mkAscon_engine rg_state_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+187,"mkAscon_engine rg_state_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+189,"mkAscon_engine rg_state_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+190,"mkAscon_engine rg_state_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+192,"mkAscon_engine rg_state_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+194,"mkAscon_engine rg_state_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+195,"mkAscon_engine rg_state_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+197,"mkAscon_engine rg_state_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+199,"mkAscon_engine rg_state_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+200,"mkAscon_engine rg_state_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+202,"mkAscon_engine rg_state_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+204,"mkAscon_engine rg_state_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+205,"mkAscon_engine rg_state_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+207,"mkAscon_engine rg_state_4_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+209,"mkAscon_engine rg_state_4_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+210,"mkAscon_engine select",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+211,"mkAscon_engine select_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+212,"mkAscon_engine select_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+213,"mkAscon_engine CAN_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+214,"mkAscon_engine CAN_FIRE_RL_decryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+215,"mkAscon_engine CAN_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+216,"mkAscon_engine CAN_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+217,"mkAscon_engine CAN_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+218,"mkAscon_engine CAN_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+219,"mkAscon_engine CAN_FIRE_RL_permutate_encrypt_decrypt_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+220,"mkAscon_engine CAN_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+221,"mkAscon_engine WILL_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+222,"mkAscon_engine WILL_FIRE_RL_decryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+223,"mkAscon_engine WILL_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+224,"mkAscon_engine WILL_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+225,"mkAscon_engine WILL_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+226,"mkAscon_engine WILL_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+227,"mkAscon_engine WILL_FIRE_RL_permutate_encrypt_decrypt_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+228,"mkAscon_engine WILL_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+229,"mkAscon_engine MUX_rg_state_0_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+231,"mkAscon_engine MUX_rg_state_0_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+233,"mkAscon_engine MUX_rg_state_0_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+235,"mkAscon_engine MUX_rg_state_0_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+237,"mkAscon_engine MUX_rg_state_0_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+239,"mkAscon_engine MUX_rg_state_1_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+241,"mkAscon_engine MUX_rg_state_1_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+243,"mkAscon_engine MUX_rg_state_1_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+245,"mkAscon_engine MUX_rg_state_1_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+247,"mkAscon_engine MUX_rg_state_1_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+249,"mkAscon_engine MUX_rg_state_2_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+251,"mkAscon_engine MUX_rg_state_2_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+253,"mkAscon_engine MUX_rg_state_2_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+255,"mkAscon_engine MUX_rg_state_2_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+257,"mkAscon_engine MUX_rg_state_3_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+259,"mkAscon_engine MUX_rg_state_3_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+261,"mkAscon_engine MUX_rg_state_3_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+263,"mkAscon_engine MUX_rg_state_3_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+265,"mkAscon_engine MUX_rg_state_4_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+267,"mkAscon_engine MUX_rg_state_4_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+269,"mkAscon_engine MUX_rg_state_4_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+271,"mkAscon_engine MUX_rg_state_4_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+273,"mkAscon_engine MUX_counter_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+274,"mkAscon_engine MUX_counter_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+275,"mkAscon_engine MUX_counter_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+276,"mkAscon_engine MUX_fsm_state_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
        tracep->declBit(c+277,"mkAscon_engine MUX_counter_write_1__SEL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+278,"mkAscon_engine MUX_counter_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+279,"mkAscon_engine MUX_counter_write_1__SEL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+280,"mkAscon_engine MUX_fsm_state_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+281,"mkAscon_engine MUX_fsm_state_write_1__SEL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+282,"mkAscon_engine MUX_fsm_state_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+283,"mkAscon_engine MUX_fsm_state_write_1__SEL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+284,"mkAscon_engine MUX_fsm_state_write_1__SEL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+285,"mkAscon_engine MUX_fsm_state_write_1__SEL_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+286,"mkAscon_engine MUX_fsm_state_write_1__SEL_8",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+287,"mkAscon_engine MUX_rg_state_0_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+288,"mkAscon_engine MUX_rg_state_2_write_1__PSEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+289,"mkAscon_engine MUX_rg_state_2_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+290,"mkAscon_engine MUX_rg_state_3_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+291,"mkAscon_engine MUX_rg_state_4_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+292,"mkAscon_engine y__h20548",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+294,"mkAscon_engine y__h25671",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declArray(c+296,"mkAscon_engine lv_finalized_key__h24489",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+306,"mkAscon_engine lv_updated_finalized_data__h24455",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+316,"mkAscon_engine packed_pre_finalized_data__h23783",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+326,"mkAscon_engine padded_key__h1678",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+336,"mkAscon_engine rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___d49",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declQuad(c+346,"mkAscon_engine IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___d33",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+348,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___d15",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+350,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d23",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+352,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d27",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+354,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___d19",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+356,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d102",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+358,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d108",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+360,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d11",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+362,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d116",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+364,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d37",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+366,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d45",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+368,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d61",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+370,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d69",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+372,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d94",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+374,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d76",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+376,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d84",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+378,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d181",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+380,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d189",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+382,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d281",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+384,"mkAscon_engine din__h10845",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+386,"mkAscon_engine encryption0__h16560",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+388,"mkAscon_engine encryption1__h16561",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+390,"mkAscon_engine encryption_tag0__h29252",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+392,"mkAscon_engine encryption_tag1__h29253",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+394,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d136",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+396,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d263",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+398,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d198",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+400,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d206",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+402,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d284",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+404,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d143",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+406,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d151",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+408,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d219",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+410,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d269",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+412,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d165",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+414,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d173",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+416,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d278",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+418,"mkAscon_engine x__h12058",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+420,"mkAscon_engine x__h21414",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+422,"mkAscon_engine x__h21416",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+424,"mkAscon_engine x__h21418",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+426,"mkAscon_engine x__h21420",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+428,"mkAscon_engine x__h21541",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+430,"mkAscon_engine x__h21543",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+432,"mkAscon_engine x__h21545",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+434,"mkAscon_engine x__h21547",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+436,"mkAscon_engine x__h21549",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+438,"mkAscon_engine x__h21551",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+440,"mkAscon_engine x__h21681",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+442,"mkAscon_engine x__h21755",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+444,"mkAscon_engine x__h21757",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+446,"mkAscon_engine x__h22091",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+448,"mkAscon_engine x__h22332",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+450,"mkAscon_engine x__h22573",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+452,"mkAscon_engine x__h22814",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+454,"mkAscon_engine x__h26537",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+456,"mkAscon_engine x__h26539",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+458,"mkAscon_engine x__h26541",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+460,"mkAscon_engine x__h26543",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+462,"mkAscon_engine x__h26545",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+464,"mkAscon_engine x__h26664",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+466,"mkAscon_engine x__h26666",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+468,"mkAscon_engine x__h26668",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+470,"mkAscon_engine x__h26670",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+472,"mkAscon_engine x__h26672",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+474,"mkAscon_engine x__h26674",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+476,"mkAscon_engine x__h26804",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+478,"mkAscon_engine x__h26806",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+480,"mkAscon_engine x__h26808",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+482,"mkAscon_engine x__h26878",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+484,"mkAscon_engine x__h26880",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+486,"mkAscon_engine x__h26882",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+488,"mkAscon_engine x__h26884",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+490,"mkAscon_engine x__h26886",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+492,"mkAscon_engine x__h26888",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+494,"mkAscon_engine x__h26994",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+496,"mkAscon_engine x__h26996",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+498,"mkAscon_engine x__h26998",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+500,"mkAscon_engine x__h27000",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+502,"mkAscon_engine x__h27214",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+504,"mkAscon_engine x__h27455",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+506,"mkAscon_engine x__h27696",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+508,"mkAscon_engine x__h27937",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+510,"mkAscon_engine x__h28178",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+512,"mkAscon_engine x__h28180",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+514,"mkAscon_engine x__h4600",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+516,"mkAscon_engine x__h4602",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+518,"mkAscon_engine x__h4604",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+520,"mkAscon_engine x__h4606",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+522,"mkAscon_engine x__h4608",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+524,"mkAscon_engine x__h4610",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+526,"mkAscon_engine x__h4727",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+528,"mkAscon_engine x__h4729",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+530,"mkAscon_engine x__h4731",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+532,"mkAscon_engine x__h4733",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+534,"mkAscon_engine x__h4735",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+536,"mkAscon_engine x__h4737",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+538,"mkAscon_engine x__h4867",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+540,"mkAscon_engine x__h4869",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+542,"mkAscon_engine x__h4871",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+544,"mkAscon_engine x__h4941",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+546,"mkAscon_engine x__h4943",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+548,"mkAscon_engine x__h4945",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+550,"mkAscon_engine x__h4947",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+552,"mkAscon_engine x__h4949",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+554,"mkAscon_engine x__h4951",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+556,"mkAscon_engine x__h5057",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+558,"mkAscon_engine x__h5059",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+560,"mkAscon_engine x__h5061",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+562,"mkAscon_engine x__h5277",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+564,"mkAscon_engine x__h5518",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+566,"mkAscon_engine x__h5759",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+568,"mkAscon_engine x__h6000",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+570,"mkAscon_engine x__h6241",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+572,"mkAscon_engine x__h7531",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+574,"mkAscon_engine y__h21423",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+576,"mkAscon_engine y__h21546",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+578,"mkAscon_engine y__h21554",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+580,"mkAscon_engine y__h22092",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+582,"mkAscon_engine y__h22094",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+584,"mkAscon_engine y__h22333",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+586,"mkAscon_engine y__h22335",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+588,"mkAscon_engine y__h22574",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+590,"mkAscon_engine y__h22576",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+592,"mkAscon_engine y__h22815",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+594,"mkAscon_engine y__h22817",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+596,"mkAscon_engine y__h26546",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+598,"mkAscon_engine y__h26669",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+600,"mkAscon_engine y__h26673",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+602,"mkAscon_engine y__h26677",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+604,"mkAscon_engine y__h26889",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+606,"mkAscon_engine y__h26997",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+608,"mkAscon_engine y__h27215",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+610,"mkAscon_engine y__h27217",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+612,"mkAscon_engine y__h27456",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+614,"mkAscon_engine y__h27458",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+616,"mkAscon_engine y__h27697",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+618,"mkAscon_engine y__h27699",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+620,"mkAscon_engine y__h27938",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+622,"mkAscon_engine y__h27940",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+624,"mkAscon_engine y__h28179",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+626,"mkAscon_engine y__h28181",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+628,"mkAscon_engine y__h4605",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+630,"mkAscon_engine y__h4609",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+632,"mkAscon_engine y__h4732",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+634,"mkAscon_engine y__h4736",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+636,"mkAscon_engine y__h4740",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+638,"mkAscon_engine y__h4952",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+640,"mkAscon_engine y__h5278",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+642,"mkAscon_engine y__h5280",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+644,"mkAscon_engine y__h5519",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+646,"mkAscon_engine y__h5521",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+648,"mkAscon_engine y__h5760",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+650,"mkAscon_engine y__h5762",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+652,"mkAscon_engine y__h6001",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+654,"mkAscon_engine y__h6003",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+656,"mkAscon_engine y__h6242",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+658,"mkAscon_engine y__h6244",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+660,"mkAscon_engine x__h20564",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+661,"mkAscon_engine x__h25687",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+662,"mkAscon_engine x__h29164",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBit(c+663,"mkAscon_engine counter_ULT_12___d4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    }
}

void Vtop::traceRegister(VerilatedFst* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vtop::traceFullTop0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vtop::traceFullSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullBit(oldp+1,(vlTOPp->CLK));
        tracep->fullBit(oldp+2,(vlTOPp->RST_N));
        tracep->fullWData(oldp+3,(vlTOPp->input_function_plaintext),128);
        tracep->fullWData(oldp+7,(vlTOPp->input_function_associated_data),128);
        tracep->fullWData(oldp+11,(vlTOPp->input_function_key),128);
        tracep->fullWData(oldp+15,(vlTOPp->input_function_nonce),128);
        tracep->fullBit(oldp+19,(vlTOPp->input_function_mode));
        tracep->fullBit(oldp+20,(vlTOPp->EN_input_function));
        tracep->fullBit(oldp+21,(vlTOPp->RDY_input_function));
        tracep->fullWData(oldp+22,(vlTOPp->ciphertext),128);
        tracep->fullBit(oldp+26,(vlTOPp->RDY_ciphertext));
        tracep->fullWData(oldp+27,(vlTOPp->decrypted_data),128);
        tracep->fullBit(oldp+31,(vlTOPp->RDY_decrypted_data));
        tracep->fullWData(oldp+32,(vlTOPp->tag),128);
        tracep->fullBit(oldp+36,(vlTOPp->RDY_tag));
        tracep->fullWData(oldp+37,(vlTOPp->decrypted_tag),128);
        tracep->fullBit(oldp+41,(vlTOPp->RDY_decrypted_tag));
        tracep->fullBit(oldp+42,(vlTOPp->mkAscon_engine__DOT__CLK));
        tracep->fullBit(oldp+43,(vlTOPp->mkAscon_engine__DOT__RST_N));
        tracep->fullWData(oldp+44,(vlTOPp->mkAscon_engine__DOT__input_function_plaintext),128);
        tracep->fullWData(oldp+48,(vlTOPp->mkAscon_engine__DOT__input_function_associated_data),128);
        tracep->fullWData(oldp+52,(vlTOPp->mkAscon_engine__DOT__input_function_key),128);
        tracep->fullWData(oldp+56,(vlTOPp->mkAscon_engine__DOT__input_function_nonce),128);
        tracep->fullBit(oldp+60,(vlTOPp->mkAscon_engine__DOT__input_function_mode));
        tracep->fullBit(oldp+61,(vlTOPp->mkAscon_engine__DOT__EN_input_function));
        tracep->fullBit(oldp+62,(vlTOPp->mkAscon_engine__DOT__RDY_input_function));
        tracep->fullWData(oldp+63,(vlTOPp->mkAscon_engine__DOT__ciphertext),128);
        tracep->fullBit(oldp+67,(vlTOPp->mkAscon_engine__DOT__RDY_ciphertext));
        tracep->fullWData(oldp+68,(vlTOPp->mkAscon_engine__DOT__decrypted_data),128);
        tracep->fullBit(oldp+72,(vlTOPp->mkAscon_engine__DOT__RDY_decrypted_data));
        tracep->fullWData(oldp+73,(vlTOPp->mkAscon_engine__DOT__tag),128);
        tracep->fullBit(oldp+77,(vlTOPp->mkAscon_engine__DOT__RDY_tag));
        tracep->fullWData(oldp+78,(vlTOPp->mkAscon_engine__DOT__decrypted_tag),128);
        tracep->fullBit(oldp+82,(vlTOPp->mkAscon_engine__DOT__RDY_decrypted_tag));
        tracep->fullCData(oldp+83,(vlTOPp->mkAscon_engine__DOT__counter),4);
        tracep->fullCData(oldp+84,(vlTOPp->mkAscon_engine__DOT__counter_D_IN),4);
        tracep->fullBit(oldp+85,(vlTOPp->mkAscon_engine__DOT__counter_EN));
        tracep->fullCData(oldp+86,(vlTOPp->mkAscon_engine__DOT__fsm_state),3);
        tracep->fullCData(oldp+87,(vlTOPp->mkAscon_engine__DOT__fsm_state_D_IN),3);
        tracep->fullBit(oldp+88,(vlTOPp->mkAscon_engine__DOT__fsm_state_EN));
        tracep->fullQData(oldp+89,(vlTOPp->mkAscon_engine__DOT__iv_constant),64);
        tracep->fullQData(oldp+91,(vlTOPp->mkAscon_engine__DOT__iv_constant_D_IN),64);
        tracep->fullBit(oldp+93,(vlTOPp->mkAscon_engine__DOT__iv_constant_EN));
        tracep->fullBit(oldp+94,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext));
        tracep->fullBit(oldp+95,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_D_IN));
        tracep->fullBit(oldp+96,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_EN));
        tracep->fullBit(oldp+97,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_data));
        tracep->fullBit(oldp+98,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_data_D_IN));
        tracep->fullBit(oldp+99,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_data_EN));
        tracep->fullBit(oldp+100,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_tag));
        tracep->fullBit(oldp+101,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_tag_D_IN));
        tracep->fullBit(oldp+102,(vlTOPp->mkAscon_engine__DOT__ready_decrypted_tag_EN));
        tracep->fullBit(oldp+103,(vlTOPp->mkAscon_engine__DOT__ready_tag));
        tracep->fullBit(oldp+104,(vlTOPp->mkAscon_engine__DOT__ready_tag_D_IN));
        tracep->fullBit(oldp+105,(vlTOPp->mkAscon_engine__DOT__ready_tag_EN));
        tracep->fullBit(oldp+106,(vlTOPp->mkAscon_engine__DOT__req_associated_data));
        tracep->fullBit(oldp+107,(vlTOPp->mkAscon_engine__DOT__req_associated_data_D_IN));
        tracep->fullBit(oldp+108,(vlTOPp->mkAscon_engine__DOT__req_associated_data_EN));
        tracep->fullQData(oldp+109,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_0),64);
        tracep->fullQData(oldp+111,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_0_D_IN),64);
        tracep->fullBit(oldp+113,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_0_EN));
        tracep->fullQData(oldp+114,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_1),64);
        tracep->fullQData(oldp+116,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_1_D_IN),64);
        tracep->fullBit(oldp+118,(vlTOPp->mkAscon_engine__DOT__rg_decrypted_data_1_EN));
        tracep->fullQData(oldp+119,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_0),64);
        tracep->fullQData(oldp+121,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_0_D_IN),64);
        tracep->fullBit(oldp+123,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_0_EN));
        tracep->fullQData(oldp+124,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_1),64);
        tracep->fullQData(oldp+126,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_1_D_IN),64);
        tracep->fullBit(oldp+128,(vlTOPp->mkAscon_engine__DOT__rg_decryption_tag_1_EN));
        tracep->fullQData(oldp+129,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0),64);
        tracep->fullQData(oldp+131,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_D_IN),64);
        tracep->fullBit(oldp+133,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_EN));
        tracep->fullQData(oldp+134,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1),64);
        tracep->fullQData(oldp+136,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_D_IN),64);
        tracep->fullBit(oldp+138,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_EN));
        tracep->fullQData(oldp+139,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0),64);
        tracep->fullQData(oldp+141,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_D_IN),64);
        tracep->fullBit(oldp+143,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_EN));
        tracep->fullQData(oldp+144,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1),64);
        tracep->fullQData(oldp+146,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_D_IN),64);
        tracep->fullBit(oldp+148,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_EN));
        tracep->fullWData(oldp+149,(vlTOPp->mkAscon_engine__DOT__rg_interface_0),128);
        tracep->fullWData(oldp+153,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_D_IN),128);
        tracep->fullBit(oldp+157,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_EN));
        tracep->fullWData(oldp+158,(vlTOPp->mkAscon_engine__DOT__rg_interface_1),128);
        tracep->fullWData(oldp+162,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_D_IN),128);
        tracep->fullBit(oldp+166,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_EN));
        tracep->fullWData(oldp+167,(vlTOPp->mkAscon_engine__DOT__rg_interface_2),128);
        tracep->fullWData(oldp+171,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_D_IN),128);
        tracep->fullBit(oldp+175,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_EN));
        tracep->fullWData(oldp+176,(vlTOPp->mkAscon_engine__DOT__rg_interface_3),128);
        tracep->fullWData(oldp+180,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_D_IN),128);
        tracep->fullBit(oldp+184,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_EN));
        tracep->fullQData(oldp+185,(vlTOPp->mkAscon_engine__DOT__rg_state_0),64);
        tracep->fullQData(oldp+187,(vlTOPp->mkAscon_engine__DOT__rg_state_0_D_IN),64);
        tracep->fullBit(oldp+189,(vlTOPp->mkAscon_engine__DOT__rg_state_0_EN));
        tracep->fullQData(oldp+190,(vlTOPp->mkAscon_engine__DOT__rg_state_1),64);
        tracep->fullQData(oldp+192,(vlTOPp->mkAscon_engine__DOT__rg_state_1_D_IN),64);
        tracep->fullBit(oldp+194,(vlTOPp->mkAscon_engine__DOT__rg_state_1_EN));
        tracep->fullQData(oldp+195,(vlTOPp->mkAscon_engine__DOT__rg_state_2),64);
        tracep->fullQData(oldp+197,(vlTOPp->mkAscon_engine__DOT__rg_state_2_D_IN),64);
        tracep->fullBit(oldp+199,(vlTOPp->mkAscon_engine__DOT__rg_state_2_EN));
        tracep->fullQData(oldp+200,(vlTOPp->mkAscon_engine__DOT__rg_state_3),64);
        tracep->fullQData(oldp+202,(vlTOPp->mkAscon_engine__DOT__rg_state_3_D_IN),64);
        tracep->fullBit(oldp+204,(vlTOPp->mkAscon_engine__DOT__rg_state_3_EN));
        tracep->fullQData(oldp+205,(vlTOPp->mkAscon_engine__DOT__rg_state_4),64);
        tracep->fullQData(oldp+207,(vlTOPp->mkAscon_engine__DOT__rg_state_4_D_IN),64);
        tracep->fullBit(oldp+209,(vlTOPp->mkAscon_engine__DOT__rg_state_4_EN));
        tracep->fullBit(oldp+210,(vlTOPp->mkAscon_engine__DOT__select));
        tracep->fullBit(oldp+211,(vlTOPp->mkAscon_engine__DOT__select_D_IN));
        tracep->fullBit(oldp+212,(vlTOPp->mkAscon_engine__DOT__select_EN));
        tracep->fullBit(oldp+213,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+214,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_decryption_state));
        tracep->fullBit(oldp+215,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+216,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+217,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+218,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+219,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_encrypt_decrypt_state));
        tracep->fullBit(oldp+220,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_input_function));
        tracep->fullBit(oldp+221,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+222,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_decryption_state));
        tracep->fullBit(oldp+223,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+224,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+225,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+226,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+227,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_encrypt_decrypt_state));
        tracep->fullBit(oldp+228,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_input_function));
        tracep->fullQData(oldp+229,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+231,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+233,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+235,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+237,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+239,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+241,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+243,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+245,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+247,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+249,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+251,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+253,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+255,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+257,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+259,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+261,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+263,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+265,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+267,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+269,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+271,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_6),64);
        tracep->fullCData(oldp+273,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_2),4);
        tracep->fullCData(oldp+274,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_4),4);
        tracep->fullCData(oldp+275,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_5),4);
        tracep->fullCData(oldp+276,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FVAL_6),3);
        tracep->fullBit(oldp+277,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_1));
        tracep->fullBit(oldp+278,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_2));
        tracep->fullBit(oldp+279,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_3));
        tracep->fullBit(oldp+280,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_2));
        tracep->fullBit(oldp+281,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_3));
        tracep->fullBit(oldp+282,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_4));
        tracep->fullBit(oldp+283,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_5));
        tracep->fullBit(oldp+284,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_6));
        tracep->fullBit(oldp+285,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_7));
        tracep->fullBit(oldp+286,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_8));
        tracep->fullBit(oldp+287,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FSEL_2));
        tracep->fullBit(oldp+288,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FPSEL_4));
        tracep->fullBit(oldp+289,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FSEL_4));
        tracep->fullBit(oldp+290,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FSEL_4));
        tracep->fullBit(oldp+291,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FSEL_4));
        tracep->fullQData(oldp+292,(vlTOPp->mkAscon_engine__DOT__y___05Fh20548),64);
        tracep->fullQData(oldp+294,(vlTOPp->mkAscon_engine__DOT__y___05Fh25671),64);
        tracep->fullWData(oldp+296,(vlTOPp->mkAscon_engine__DOT__lv_finalized_key___05Fh24489),320);
        tracep->fullWData(oldp+306,(vlTOPp->mkAscon_engine__DOT__lv_updated_finalized_data___05Fh24455),320);
        tracep->fullWData(oldp+316,(vlTOPp->mkAscon_engine__DOT__packed_pre_finalized_data___05Fh23783),320);
        tracep->fullWData(oldp+326,(vlTOPp->mkAscon_engine__DOT__padded_key___05Fh1678),320);
        tracep->fullWData(oldp+336,(vlTOPp->mkAscon_engine__DOT__rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___05F_d49),320);
        tracep->fullQData(oldp+346,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___05F_d33),64);
        tracep->fullQData(oldp+348,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___05F_d15),64);
        tracep->fullQData(oldp+350,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d23),64);
        tracep->fullQData(oldp+352,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d27),64);
        tracep->fullQData(oldp+354,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___05F_d19),64);
        tracep->fullQData(oldp+356,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d102),64);
        tracep->fullQData(oldp+358,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d108),64);
        tracep->fullQData(oldp+360,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d11),64);
        tracep->fullQData(oldp+362,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d116),64);
        tracep->fullQData(oldp+364,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d37),64);
        tracep->fullQData(oldp+366,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d45),64);
        tracep->fullQData(oldp+368,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d61),64);
        tracep->fullQData(oldp+370,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d69),64);
        tracep->fullQData(oldp+372,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d94),64);
        tracep->fullQData(oldp+374,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d76),64);
        tracep->fullQData(oldp+376,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d84),64);
        tracep->fullQData(oldp+378,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d181),64);
        tracep->fullQData(oldp+380,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d189),64);
        tracep->fullQData(oldp+382,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d281),64);
        tracep->fullQData(oldp+384,(vlTOPp->mkAscon_engine__DOT__din___05Fh10845),64);
        tracep->fullQData(oldp+386,(vlTOPp->mkAscon_engine__DOT__encryption0___05Fh16560),64);
        tracep->fullQData(oldp+388,(vlTOPp->mkAscon_engine__DOT__encryption1___05Fh16561),64);
        tracep->fullQData(oldp+390,(vlTOPp->mkAscon_engine__DOT__encryption_tag0___05Fh29252),64);
        tracep->fullQData(oldp+392,(vlTOPp->mkAscon_engine__DOT__encryption_tag1___05Fh29253),64);
        tracep->fullQData(oldp+394,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d136),64);
        tracep->fullQData(oldp+396,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d263),64);
        tracep->fullQData(oldp+398,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d198),64);
        tracep->fullQData(oldp+400,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d206),64);
        tracep->fullQData(oldp+402,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d284),64);
        tracep->fullQData(oldp+404,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d143),64);
        tracep->fullQData(oldp+406,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d151),64);
        tracep->fullQData(oldp+408,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d219),64);
        tracep->fullQData(oldp+410,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d269),64);
        tracep->fullQData(oldp+412,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d165),64);
        tracep->fullQData(oldp+414,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d173),64);
        tracep->fullQData(oldp+416,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d278),64);
        tracep->fullQData(oldp+418,(vlTOPp->mkAscon_engine__DOT__x___05Fh12058),64);
        tracep->fullQData(oldp+420,(vlTOPp->mkAscon_engine__DOT__x___05Fh21414),64);
        tracep->fullQData(oldp+422,(vlTOPp->mkAscon_engine__DOT__x___05Fh21416),64);
        tracep->fullQData(oldp+424,(vlTOPp->mkAscon_engine__DOT__x___05Fh21418),64);
        tracep->fullQData(oldp+426,(vlTOPp->mkAscon_engine__DOT__x___05Fh21420),64);
        tracep->fullQData(oldp+428,(vlTOPp->mkAscon_engine__DOT__x___05Fh21541),64);
        tracep->fullQData(oldp+430,(vlTOPp->mkAscon_engine__DOT__x___05Fh21543),64);
        tracep->fullQData(oldp+432,(vlTOPp->mkAscon_engine__DOT__x___05Fh21545),64);
        tracep->fullQData(oldp+434,(vlTOPp->mkAscon_engine__DOT__x___05Fh21547),64);
        tracep->fullQData(oldp+436,(vlTOPp->mkAscon_engine__DOT__x___05Fh21549),64);
        tracep->fullQData(oldp+438,(vlTOPp->mkAscon_engine__DOT__x___05Fh21551),64);
        tracep->fullQData(oldp+440,(vlTOPp->mkAscon_engine__DOT__x___05Fh21681),64);
        tracep->fullQData(oldp+442,(vlTOPp->mkAscon_engine__DOT__x___05Fh21755),64);
        tracep->fullQData(oldp+444,(vlTOPp->mkAscon_engine__DOT__x___05Fh21757),64);
        tracep->fullQData(oldp+446,(vlTOPp->mkAscon_engine__DOT__x___05Fh22091),64);
        tracep->fullQData(oldp+448,(vlTOPp->mkAscon_engine__DOT__x___05Fh22332),64);
        tracep->fullQData(oldp+450,(vlTOPp->mkAscon_engine__DOT__x___05Fh22573),64);
        tracep->fullQData(oldp+452,(vlTOPp->mkAscon_engine__DOT__x___05Fh22814),64);
        tracep->fullQData(oldp+454,(vlTOPp->mkAscon_engine__DOT__x___05Fh26537),64);
        tracep->fullQData(oldp+456,(vlTOPp->mkAscon_engine__DOT__x___05Fh26539),64);
        tracep->fullQData(oldp+458,(vlTOPp->mkAscon_engine__DOT__x___05Fh26541),64);
        tracep->fullQData(oldp+460,(vlTOPp->mkAscon_engine__DOT__x___05Fh26543),64);
        tracep->fullQData(oldp+462,(vlTOPp->mkAscon_engine__DOT__x___05Fh26545),64);
        tracep->fullQData(oldp+464,(vlTOPp->mkAscon_engine__DOT__x___05Fh26664),64);
        tracep->fullQData(oldp+466,(vlTOPp->mkAscon_engine__DOT__x___05Fh26666),64);
        tracep->fullQData(oldp+468,(vlTOPp->mkAscon_engine__DOT__x___05Fh26668),64);
        tracep->fullQData(oldp+470,(vlTOPp->mkAscon_engine__DOT__x___05Fh26670),64);
        tracep->fullQData(oldp+472,(vlTOPp->mkAscon_engine__DOT__x___05Fh26672),64);
        tracep->fullQData(oldp+474,(vlTOPp->mkAscon_engine__DOT__x___05Fh26674),64);
        tracep->fullQData(oldp+476,(vlTOPp->mkAscon_engine__DOT__x___05Fh26804),64);
        tracep->fullQData(oldp+478,(vlTOPp->mkAscon_engine__DOT__x___05Fh26806),64);
        tracep->fullQData(oldp+480,(vlTOPp->mkAscon_engine__DOT__x___05Fh26808),64);
        tracep->fullQData(oldp+482,(vlTOPp->mkAscon_engine__DOT__x___05Fh26878),64);
        tracep->fullQData(oldp+484,(vlTOPp->mkAscon_engine__DOT__x___05Fh26880),64);
        tracep->fullQData(oldp+486,(vlTOPp->mkAscon_engine__DOT__x___05Fh26882),64);
        tracep->fullQData(oldp+488,(vlTOPp->mkAscon_engine__DOT__x___05Fh26884),64);
        tracep->fullQData(oldp+490,(vlTOPp->mkAscon_engine__DOT__x___05Fh26886),64);
        tracep->fullQData(oldp+492,(vlTOPp->mkAscon_engine__DOT__x___05Fh26888),64);
        tracep->fullQData(oldp+494,(vlTOPp->mkAscon_engine__DOT__x___05Fh26994),64);
        tracep->fullQData(oldp+496,(vlTOPp->mkAscon_engine__DOT__x___05Fh26996),64);
        tracep->fullQData(oldp+498,(vlTOPp->mkAscon_engine__DOT__x___05Fh26998),64);
        tracep->fullQData(oldp+500,(vlTOPp->mkAscon_engine__DOT__x___05Fh27000),64);
        tracep->fullQData(oldp+502,(vlTOPp->mkAscon_engine__DOT__x___05Fh27214),64);
        tracep->fullQData(oldp+504,(vlTOPp->mkAscon_engine__DOT__x___05Fh27455),64);
        tracep->fullQData(oldp+506,(vlTOPp->mkAscon_engine__DOT__x___05Fh27696),64);
        tracep->fullQData(oldp+508,(vlTOPp->mkAscon_engine__DOT__x___05Fh27937),64);
        tracep->fullQData(oldp+510,(vlTOPp->mkAscon_engine__DOT__x___05Fh28178),64);
        tracep->fullQData(oldp+512,(vlTOPp->mkAscon_engine__DOT__x___05Fh28180),64);
        tracep->fullQData(oldp+514,(vlTOPp->mkAscon_engine__DOT__x___05Fh4600),64);
        tracep->fullQData(oldp+516,(vlTOPp->mkAscon_engine__DOT__x___05Fh4602),64);
        tracep->fullQData(oldp+518,(vlTOPp->mkAscon_engine__DOT__x___05Fh4604),64);
        tracep->fullQData(oldp+520,(vlTOPp->mkAscon_engine__DOT__x___05Fh4606),64);
        tracep->fullQData(oldp+522,(vlTOPp->mkAscon_engine__DOT__x___05Fh4608),64);
        tracep->fullQData(oldp+524,(vlTOPp->mkAscon_engine__DOT__x___05Fh4610),64);
        tracep->fullQData(oldp+526,(vlTOPp->mkAscon_engine__DOT__x___05Fh4727),64);
        tracep->fullQData(oldp+528,(vlTOPp->mkAscon_engine__DOT__x___05Fh4729),64);
        tracep->fullQData(oldp+530,(vlTOPp->mkAscon_engine__DOT__x___05Fh4731),64);
        tracep->fullQData(oldp+532,(vlTOPp->mkAscon_engine__DOT__x___05Fh4733),64);
        tracep->fullQData(oldp+534,(vlTOPp->mkAscon_engine__DOT__x___05Fh4735),64);
        tracep->fullQData(oldp+536,(vlTOPp->mkAscon_engine__DOT__x___05Fh4737),64);
        tracep->fullQData(oldp+538,(vlTOPp->mkAscon_engine__DOT__x___05Fh4867),64);
        tracep->fullQData(oldp+540,(vlTOPp->mkAscon_engine__DOT__x___05Fh4869),64);
        tracep->fullQData(oldp+542,(vlTOPp->mkAscon_engine__DOT__x___05Fh4871),64);
        tracep->fullQData(oldp+544,(vlTOPp->mkAscon_engine__DOT__x___05Fh4941),64);
        tracep->fullQData(oldp+546,(vlTOPp->mkAscon_engine__DOT__x___05Fh4943),64);
        tracep->fullQData(oldp+548,(vlTOPp->mkAscon_engine__DOT__x___05Fh4945),64);
        tracep->fullQData(oldp+550,(vlTOPp->mkAscon_engine__DOT__x___05Fh4947),64);
        tracep->fullQData(oldp+552,(vlTOPp->mkAscon_engine__DOT__x___05Fh4949),64);
        tracep->fullQData(oldp+554,(vlTOPp->mkAscon_engine__DOT__x___05Fh4951),64);
        tracep->fullQData(oldp+556,(vlTOPp->mkAscon_engine__DOT__x___05Fh5057),64);
        tracep->fullQData(oldp+558,(vlTOPp->mkAscon_engine__DOT__x___05Fh5059),64);
        tracep->fullQData(oldp+560,(vlTOPp->mkAscon_engine__DOT__x___05Fh5061),64);
        tracep->fullQData(oldp+562,(vlTOPp->mkAscon_engine__DOT__x___05Fh5277),64);
        tracep->fullQData(oldp+564,(vlTOPp->mkAscon_engine__DOT__x___05Fh5518),64);
        tracep->fullQData(oldp+566,(vlTOPp->mkAscon_engine__DOT__x___05Fh5759),64);
        tracep->fullQData(oldp+568,(vlTOPp->mkAscon_engine__DOT__x___05Fh6000),64);
        tracep->fullQData(oldp+570,(vlTOPp->mkAscon_engine__DOT__x___05Fh6241),64);
        tracep->fullQData(oldp+572,(vlTOPp->mkAscon_engine__DOT__x___05Fh7531),64);
        tracep->fullQData(oldp+574,(vlTOPp->mkAscon_engine__DOT__y___05Fh21423),64);
        tracep->fullQData(oldp+576,(vlTOPp->mkAscon_engine__DOT__y___05Fh21546),64);
        tracep->fullQData(oldp+578,(vlTOPp->mkAscon_engine__DOT__y___05Fh21554),64);
        tracep->fullQData(oldp+580,(vlTOPp->mkAscon_engine__DOT__y___05Fh22092),64);
        tracep->fullQData(oldp+582,(vlTOPp->mkAscon_engine__DOT__y___05Fh22094),64);
        tracep->fullQData(oldp+584,(vlTOPp->mkAscon_engine__DOT__y___05Fh22333),64);
        tracep->fullQData(oldp+586,(vlTOPp->mkAscon_engine__DOT__y___05Fh22335),64);
        tracep->fullQData(oldp+588,(vlTOPp->mkAscon_engine__DOT__y___05Fh22574),64);
        tracep->fullQData(oldp+590,(vlTOPp->mkAscon_engine__DOT__y___05Fh22576),64);
        tracep->fullQData(oldp+592,(vlTOPp->mkAscon_engine__DOT__y___05Fh22815),64);
        tracep->fullQData(oldp+594,(vlTOPp->mkAscon_engine__DOT__y___05Fh22817),64);
        tracep->fullQData(oldp+596,(vlTOPp->mkAscon_engine__DOT__y___05Fh26546),64);
        tracep->fullQData(oldp+598,(vlTOPp->mkAscon_engine__DOT__y___05Fh26669),64);
        tracep->fullQData(oldp+600,(vlTOPp->mkAscon_engine__DOT__y___05Fh26673),64);
        tracep->fullQData(oldp+602,(vlTOPp->mkAscon_engine__DOT__y___05Fh26677),64);
        tracep->fullQData(oldp+604,(vlTOPp->mkAscon_engine__DOT__y___05Fh26889),64);
        tracep->fullQData(oldp+606,(vlTOPp->mkAscon_engine__DOT__y___05Fh26997),64);
        tracep->fullQData(oldp+608,(vlTOPp->mkAscon_engine__DOT__y___05Fh27215),64);
        tracep->fullQData(oldp+610,(vlTOPp->mkAscon_engine__DOT__y___05Fh27217),64);
        tracep->fullQData(oldp+612,(vlTOPp->mkAscon_engine__DOT__y___05Fh27456),64);
        tracep->fullQData(oldp+614,(vlTOPp->mkAscon_engine__DOT__y___05Fh27458),64);
        tracep->fullQData(oldp+616,(vlTOPp->mkAscon_engine__DOT__y___05Fh27697),64);
        tracep->fullQData(oldp+618,(vlTOPp->mkAscon_engine__DOT__y___05Fh27699),64);
        tracep->fullQData(oldp+620,(vlTOPp->mkAscon_engine__DOT__y___05Fh27938),64);
        tracep->fullQData(oldp+622,(vlTOPp->mkAscon_engine__DOT__y___05Fh27940),64);
        tracep->fullQData(oldp+624,(vlTOPp->mkAscon_engine__DOT__y___05Fh28179),64);
        tracep->fullQData(oldp+626,(vlTOPp->mkAscon_engine__DOT__y___05Fh28181),64);
        tracep->fullQData(oldp+628,(vlTOPp->mkAscon_engine__DOT__y___05Fh4605),64);
        tracep->fullQData(oldp+630,(vlTOPp->mkAscon_engine__DOT__y___05Fh4609),64);
        tracep->fullQData(oldp+632,(vlTOPp->mkAscon_engine__DOT__y___05Fh4732),64);
        tracep->fullQData(oldp+634,(vlTOPp->mkAscon_engine__DOT__y___05Fh4736),64);
        tracep->fullQData(oldp+636,(vlTOPp->mkAscon_engine__DOT__y___05Fh4740),64);
        tracep->fullQData(oldp+638,(vlTOPp->mkAscon_engine__DOT__y___05Fh4952),64);
        tracep->fullQData(oldp+640,(vlTOPp->mkAscon_engine__DOT__y___05Fh5278),64);
        tracep->fullQData(oldp+642,(vlTOPp->mkAscon_engine__DOT__y___05Fh5280),64);
        tracep->fullQData(oldp+644,(vlTOPp->mkAscon_engine__DOT__y___05Fh5519),64);
        tracep->fullQData(oldp+646,(vlTOPp->mkAscon_engine__DOT__y___05Fh5521),64);
        tracep->fullQData(oldp+648,(vlTOPp->mkAscon_engine__DOT__y___05Fh5760),64);
        tracep->fullQData(oldp+650,(vlTOPp->mkAscon_engine__DOT__y___05Fh5762),64);
        tracep->fullQData(oldp+652,(vlTOPp->mkAscon_engine__DOT__y___05Fh6001),64);
        tracep->fullQData(oldp+654,(vlTOPp->mkAscon_engine__DOT__y___05Fh6003),64);
        tracep->fullQData(oldp+656,(vlTOPp->mkAscon_engine__DOT__y___05Fh6242),64);
        tracep->fullQData(oldp+658,(vlTOPp->mkAscon_engine__DOT__y___05Fh6244),64);
        tracep->fullCData(oldp+660,(vlTOPp->mkAscon_engine__DOT__x___05Fh20564),4);
        tracep->fullCData(oldp+661,(vlTOPp->mkAscon_engine__DOT__x___05Fh25687),4);
        tracep->fullCData(oldp+662,(vlTOPp->mkAscon_engine__DOT__x___05Fh29164),4);
        tracep->fullBit(oldp+663,(vlTOPp->mkAscon_engine__DOT__counter_ULT_12___05F_d4));
    }
}
