// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


//======================

void Vtop::trace(VerilatedFstC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vtop::traceInit(void* userp, VerilatedFst* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vtop::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vtop::traceInitTop(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vtop::traceInitSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+1,"CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+2,"RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+3,"input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+7,"input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+11,"input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+15,"input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+19,"EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+20,"RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+21,"ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+25,"RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+26,"tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+30,"RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+31,"mkAscon_engine CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+32,"mkAscon_engine RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+33,"mkAscon_engine input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+37,"mkAscon_engine input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+41,"mkAscon_engine input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+45,"mkAscon_engine input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+49,"mkAscon_engine EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+50,"mkAscon_engine RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+51,"mkAscon_engine ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+55,"mkAscon_engine RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+56,"mkAscon_engine tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+60,"mkAscon_engine RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+61,"mkAscon_engine counter",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBus(c+62,"mkAscon_engine counter_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBit(c+63,"mkAscon_engine counter_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+64,"mkAscon_engine fsm_state",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBus(c+65,"mkAscon_engine fsm_state_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBit(c+66,"mkAscon_engine fsm_state_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+67,"mkAscon_engine iv_constant",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+69,"mkAscon_engine iv_constant_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+71,"mkAscon_engine iv_constant_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+72,"mkAscon_engine ready_ciphertext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+73,"mkAscon_engine ready_ciphertext_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+74,"mkAscon_engine ready_ciphertext_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+75,"mkAscon_engine ready_tag",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+76,"mkAscon_engine ready_tag_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+77,"mkAscon_engine ready_tag_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+78,"mkAscon_engine req_associated_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+79,"mkAscon_engine req_associated_data_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+80,"mkAscon_engine req_associated_data_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+81,"mkAscon_engine rg_encrypted_data_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+83,"mkAscon_engine rg_encrypted_data_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+85,"mkAscon_engine rg_encrypted_data_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+86,"mkAscon_engine rg_encrypted_data_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+88,"mkAscon_engine rg_encrypted_data_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+90,"mkAscon_engine rg_encrypted_data_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+91,"mkAscon_engine rg_encryption_tag_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+93,"mkAscon_engine rg_encryption_tag_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+95,"mkAscon_engine rg_encryption_tag_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+96,"mkAscon_engine rg_encryption_tag_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+98,"mkAscon_engine rg_encryption_tag_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+100,"mkAscon_engine rg_encryption_tag_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+101,"mkAscon_engine rg_interface_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+105,"mkAscon_engine rg_interface_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+109,"mkAscon_engine rg_interface_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+110,"mkAscon_engine rg_interface_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+114,"mkAscon_engine rg_interface_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+118,"mkAscon_engine rg_interface_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+119,"mkAscon_engine rg_interface_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+123,"mkAscon_engine rg_interface_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+127,"mkAscon_engine rg_interface_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+128,"mkAscon_engine rg_interface_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+132,"mkAscon_engine rg_interface_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+136,"mkAscon_engine rg_interface_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+137,"mkAscon_engine rg_state_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+139,"mkAscon_engine rg_state_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+141,"mkAscon_engine rg_state_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+142,"mkAscon_engine rg_state_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+144,"mkAscon_engine rg_state_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+146,"mkAscon_engine rg_state_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+147,"mkAscon_engine rg_state_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+149,"mkAscon_engine rg_state_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+151,"mkAscon_engine rg_state_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+152,"mkAscon_engine rg_state_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+154,"mkAscon_engine rg_state_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+156,"mkAscon_engine rg_state_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+157,"mkAscon_engine rg_state_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+159,"mkAscon_engine rg_state_4_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+161,"mkAscon_engine rg_state_4_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+162,"mkAscon_engine CAN_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+163,"mkAscon_engine CAN_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+164,"mkAscon_engine CAN_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+165,"mkAscon_engine CAN_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+166,"mkAscon_engine CAN_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+167,"mkAscon_engine CAN_FIRE_RL_permutate_encrypted_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+168,"mkAscon_engine CAN_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+169,"mkAscon_engine WILL_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+170,"mkAscon_engine WILL_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+171,"mkAscon_engine WILL_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+172,"mkAscon_engine WILL_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+173,"mkAscon_engine WILL_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+174,"mkAscon_engine WILL_FIRE_RL_permutate_encrypted_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+175,"mkAscon_engine WILL_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+176,"mkAscon_engine MUX_rg_state_0_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+178,"mkAscon_engine MUX_rg_state_0_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+180,"mkAscon_engine MUX_rg_state_0_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+182,"mkAscon_engine MUX_rg_state_0_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+184,"mkAscon_engine MUX_rg_state_0_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+186,"mkAscon_engine MUX_rg_state_1_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+188,"mkAscon_engine MUX_rg_state_1_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+190,"mkAscon_engine MUX_rg_state_1_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+192,"mkAscon_engine MUX_rg_state_1_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+194,"mkAscon_engine MUX_rg_state_1_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+196,"mkAscon_engine MUX_rg_state_2_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+198,"mkAscon_engine MUX_rg_state_2_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+200,"mkAscon_engine MUX_rg_state_2_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+202,"mkAscon_engine MUX_rg_state_2_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+204,"mkAscon_engine MUX_rg_state_3_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+206,"mkAscon_engine MUX_rg_state_3_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+208,"mkAscon_engine MUX_rg_state_3_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+210,"mkAscon_engine MUX_rg_state_3_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+212,"mkAscon_engine MUX_rg_state_4_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+214,"mkAscon_engine MUX_rg_state_4_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+216,"mkAscon_engine MUX_rg_state_4_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+218,"mkAscon_engine MUX_rg_state_4_write_1__VAL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+220,"mkAscon_engine MUX_counter_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+221,"mkAscon_engine MUX_counter_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+222,"mkAscon_engine MUX_counter_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBit(c+223,"mkAscon_engine MUX_counter_write_1__SEL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+224,"mkAscon_engine MUX_counter_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+225,"mkAscon_engine MUX_counter_write_1__SEL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+226,"mkAscon_engine MUX_fsm_state_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+227,"mkAscon_engine MUX_fsm_state_write_1__SEL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+228,"mkAscon_engine MUX_fsm_state_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+229,"mkAscon_engine MUX_fsm_state_write_1__SEL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+230,"mkAscon_engine MUX_fsm_state_write_1__SEL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+231,"mkAscon_engine MUX_fsm_state_write_1__SEL_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+232,"mkAscon_engine MUX_rg_state_0_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+233,"mkAscon_engine y__h18100",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+235,"mkAscon_engine y__h23211",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declArray(c+237,"mkAscon_engine lv_finalized_key__h22041",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+247,"mkAscon_engine lv_updated_finalized_data__h22007",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+257,"mkAscon_engine packed_pre_finalized_data__h21335",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+267,"mkAscon_engine padded_key__h1252",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+277,"mkAscon_engine rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___d49",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declQuad(c+287,"mkAscon_engine IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___d33",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+289,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___d15",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+291,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d23",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+293,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d27",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+295,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___d19",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+297,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d102",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+299,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d108",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+301,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d11",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+303,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d116",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+305,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d37",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+307,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d45",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+309,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d61",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+311,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d69",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+313,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d94",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+315,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d76",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+317,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d84",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+319,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d181",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+321,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d189",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+323,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d278",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+325,"mkAscon_engine din__h10413",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+327,"mkAscon_engine encryption0__h16082",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+329,"mkAscon_engine encryption1__h16083",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+331,"mkAscon_engine encryption_tag0__h26646",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+333,"mkAscon_engine encryption_tag1__h26647",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+335,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d136",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+337,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d260",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+339,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d198",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+341,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d206",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+343,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d281",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+345,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d143",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+347,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d151",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+349,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d219",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+351,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d266",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+353,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d165",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+355,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d173",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+357,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d275",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+359,"mkAscon_engine x__h11626",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+361,"mkAscon_engine x__h15826",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+363,"mkAscon_engine x__h16020",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+365,"mkAscon_engine x__h18966",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+367,"mkAscon_engine x__h18968",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+369,"mkAscon_engine x__h18970",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+371,"mkAscon_engine x__h18972",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+373,"mkAscon_engine x__h19093",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+375,"mkAscon_engine x__h19095",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+377,"mkAscon_engine x__h19097",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+379,"mkAscon_engine x__h19099",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+381,"mkAscon_engine x__h19101",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+383,"mkAscon_engine x__h19103",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+385,"mkAscon_engine x__h19233",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+387,"mkAscon_engine x__h19307",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+389,"mkAscon_engine x__h19309",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+391,"mkAscon_engine x__h19643",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+393,"mkAscon_engine x__h19884",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+395,"mkAscon_engine x__h20125",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+397,"mkAscon_engine x__h20366",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+399,"mkAscon_engine x__h24077",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+401,"mkAscon_engine x__h24079",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+403,"mkAscon_engine x__h24081",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+405,"mkAscon_engine x__h24083",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+407,"mkAscon_engine x__h24085",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+409,"mkAscon_engine x__h24204",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+411,"mkAscon_engine x__h24206",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+413,"mkAscon_engine x__h24208",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+415,"mkAscon_engine x__h24210",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+417,"mkAscon_engine x__h24212",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+419,"mkAscon_engine x__h24214",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+421,"mkAscon_engine x__h24344",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+423,"mkAscon_engine x__h24346",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+425,"mkAscon_engine x__h24348",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+427,"mkAscon_engine x__h24418",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+429,"mkAscon_engine x__h24420",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+431,"mkAscon_engine x__h24422",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+433,"mkAscon_engine x__h24424",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+435,"mkAscon_engine x__h24426",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+437,"mkAscon_engine x__h24428",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+439,"mkAscon_engine x__h24534",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+441,"mkAscon_engine x__h24536",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+443,"mkAscon_engine x__h24538",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+445,"mkAscon_engine x__h24540",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+447,"mkAscon_engine x__h24754",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+449,"mkAscon_engine x__h24995",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+451,"mkAscon_engine x__h25236",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+453,"mkAscon_engine x__h25477",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+455,"mkAscon_engine x__h25718",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+457,"mkAscon_engine x__h25720",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+459,"mkAscon_engine x__h4174",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+461,"mkAscon_engine x__h4176",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+463,"mkAscon_engine x__h4178",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+465,"mkAscon_engine x__h4180",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+467,"mkAscon_engine x__h4182",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+469,"mkAscon_engine x__h4184",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+471,"mkAscon_engine x__h4301",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+473,"mkAscon_engine x__h4303",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+475,"mkAscon_engine x__h4305",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+477,"mkAscon_engine x__h4307",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+479,"mkAscon_engine x__h4309",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+481,"mkAscon_engine x__h4311",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+483,"mkAscon_engine x__h4441",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+485,"mkAscon_engine x__h4443",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+487,"mkAscon_engine x__h4445",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+489,"mkAscon_engine x__h4515",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+491,"mkAscon_engine x__h4517",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+493,"mkAscon_engine x__h4519",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+495,"mkAscon_engine x__h4521",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+497,"mkAscon_engine x__h4523",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+499,"mkAscon_engine x__h4525",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+501,"mkAscon_engine x__h4631",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+503,"mkAscon_engine x__h4633",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+505,"mkAscon_engine x__h4635",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+507,"mkAscon_engine x__h4851",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+509,"mkAscon_engine x__h5092",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+511,"mkAscon_engine x__h5333",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+513,"mkAscon_engine x__h5574",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+515,"mkAscon_engine x__h5815",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+517,"mkAscon_engine x__h7099",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+519,"mkAscon_engine y__h18975",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+521,"mkAscon_engine y__h19098",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+523,"mkAscon_engine y__h19106",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+525,"mkAscon_engine y__h19644",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+527,"mkAscon_engine y__h19646",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+529,"mkAscon_engine y__h19885",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+531,"mkAscon_engine y__h19887",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+533,"mkAscon_engine y__h20126",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+535,"mkAscon_engine y__h20128",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+537,"mkAscon_engine y__h20367",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+539,"mkAscon_engine y__h20369",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+541,"mkAscon_engine y__h24086",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+543,"mkAscon_engine y__h24209",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+545,"mkAscon_engine y__h24213",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+547,"mkAscon_engine y__h24217",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+549,"mkAscon_engine y__h24429",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+551,"mkAscon_engine y__h24537",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+553,"mkAscon_engine y__h24755",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+555,"mkAscon_engine y__h24757",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+557,"mkAscon_engine y__h24996",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+559,"mkAscon_engine y__h24998",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+561,"mkAscon_engine y__h25237",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+563,"mkAscon_engine y__h25239",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+565,"mkAscon_engine y__h25478",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+567,"mkAscon_engine y__h25480",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+569,"mkAscon_engine y__h25719",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+571,"mkAscon_engine y__h25721",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+573,"mkAscon_engine y__h4179",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+575,"mkAscon_engine y__h4183",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+577,"mkAscon_engine y__h4306",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+579,"mkAscon_engine y__h4310",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+581,"mkAscon_engine y__h4314",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+583,"mkAscon_engine y__h4526",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+585,"mkAscon_engine y__h4852",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+587,"mkAscon_engine y__h4854",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+589,"mkAscon_engine y__h5093",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+591,"mkAscon_engine y__h5095",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+593,"mkAscon_engine y__h5334",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+595,"mkAscon_engine y__h5336",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+597,"mkAscon_engine y__h5575",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+599,"mkAscon_engine y__h5577",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+601,"mkAscon_engine y__h5816",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+603,"mkAscon_engine y__h5818",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+605,"mkAscon_engine x__h18116",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+606,"mkAscon_engine x__h23227",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+607,"mkAscon_engine x__h26558",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBit(c+608,"mkAscon_engine counter_ULT_12___d4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    }
}

void Vtop::traceRegister(VerilatedFst* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vtop::traceFullTop0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vtop::traceFullSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullBit(oldp+1,(vlTOPp->CLK));
        tracep->fullBit(oldp+2,(vlTOPp->RST_N));
        tracep->fullWData(oldp+3,(vlTOPp->input_function_plaintext),128);
        tracep->fullWData(oldp+7,(vlTOPp->input_function_associated_data),128);
        tracep->fullWData(oldp+11,(vlTOPp->input_function_key),128);
        tracep->fullWData(oldp+15,(vlTOPp->input_function_nonce),128);
        tracep->fullBit(oldp+19,(vlTOPp->EN_input_function));
        tracep->fullBit(oldp+20,(vlTOPp->RDY_input_function));
        tracep->fullWData(oldp+21,(vlTOPp->ciphertext),128);
        tracep->fullBit(oldp+25,(vlTOPp->RDY_ciphertext));
        tracep->fullWData(oldp+26,(vlTOPp->tag),128);
        tracep->fullBit(oldp+30,(vlTOPp->RDY_tag));
        tracep->fullBit(oldp+31,(vlTOPp->mkAscon_engine__DOT__CLK));
        tracep->fullBit(oldp+32,(vlTOPp->mkAscon_engine__DOT__RST_N));
        tracep->fullWData(oldp+33,(vlTOPp->mkAscon_engine__DOT__input_function_plaintext),128);
        tracep->fullWData(oldp+37,(vlTOPp->mkAscon_engine__DOT__input_function_associated_data),128);
        tracep->fullWData(oldp+41,(vlTOPp->mkAscon_engine__DOT__input_function_key),128);
        tracep->fullWData(oldp+45,(vlTOPp->mkAscon_engine__DOT__input_function_nonce),128);
        tracep->fullBit(oldp+49,(vlTOPp->mkAscon_engine__DOT__EN_input_function));
        tracep->fullBit(oldp+50,(vlTOPp->mkAscon_engine__DOT__RDY_input_function));
        tracep->fullWData(oldp+51,(vlTOPp->mkAscon_engine__DOT__ciphertext),128);
        tracep->fullBit(oldp+55,(vlTOPp->mkAscon_engine__DOT__RDY_ciphertext));
        tracep->fullWData(oldp+56,(vlTOPp->mkAscon_engine__DOT__tag),128);
        tracep->fullBit(oldp+60,(vlTOPp->mkAscon_engine__DOT__RDY_tag));
        tracep->fullCData(oldp+61,(vlTOPp->mkAscon_engine__DOT__counter),4);
        tracep->fullCData(oldp+62,(vlTOPp->mkAscon_engine__DOT__counter_D_IN),4);
        tracep->fullBit(oldp+63,(vlTOPp->mkAscon_engine__DOT__counter_EN));
        tracep->fullCData(oldp+64,(vlTOPp->mkAscon_engine__DOT__fsm_state),3);
        tracep->fullCData(oldp+65,(vlTOPp->mkAscon_engine__DOT__fsm_state_D_IN),3);
        tracep->fullBit(oldp+66,(vlTOPp->mkAscon_engine__DOT__fsm_state_EN));
        tracep->fullQData(oldp+67,(vlTOPp->mkAscon_engine__DOT__iv_constant),64);
        tracep->fullQData(oldp+69,(vlTOPp->mkAscon_engine__DOT__iv_constant_D_IN),64);
        tracep->fullBit(oldp+71,(vlTOPp->mkAscon_engine__DOT__iv_constant_EN));
        tracep->fullBit(oldp+72,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext));
        tracep->fullBit(oldp+73,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_D_IN));
        tracep->fullBit(oldp+74,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_EN));
        tracep->fullBit(oldp+75,(vlTOPp->mkAscon_engine__DOT__ready_tag));
        tracep->fullBit(oldp+76,(vlTOPp->mkAscon_engine__DOT__ready_tag_D_IN));
        tracep->fullBit(oldp+77,(vlTOPp->mkAscon_engine__DOT__ready_tag_EN));
        tracep->fullBit(oldp+78,(vlTOPp->mkAscon_engine__DOT__req_associated_data));
        tracep->fullBit(oldp+79,(vlTOPp->mkAscon_engine__DOT__req_associated_data_D_IN));
        tracep->fullBit(oldp+80,(vlTOPp->mkAscon_engine__DOT__req_associated_data_EN));
        tracep->fullQData(oldp+81,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0),64);
        tracep->fullQData(oldp+83,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_D_IN),64);
        tracep->fullBit(oldp+85,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_EN));
        tracep->fullQData(oldp+86,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1),64);
        tracep->fullQData(oldp+88,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_D_IN),64);
        tracep->fullBit(oldp+90,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_EN));
        tracep->fullQData(oldp+91,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0),64);
        tracep->fullQData(oldp+93,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_D_IN),64);
        tracep->fullBit(oldp+95,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_EN));
        tracep->fullQData(oldp+96,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1),64);
        tracep->fullQData(oldp+98,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_D_IN),64);
        tracep->fullBit(oldp+100,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_EN));
        tracep->fullWData(oldp+101,(vlTOPp->mkAscon_engine__DOT__rg_interface_0),128);
        tracep->fullWData(oldp+105,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_D_IN),128);
        tracep->fullBit(oldp+109,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_EN));
        tracep->fullWData(oldp+110,(vlTOPp->mkAscon_engine__DOT__rg_interface_1),128);
        tracep->fullWData(oldp+114,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_D_IN),128);
        tracep->fullBit(oldp+118,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_EN));
        tracep->fullWData(oldp+119,(vlTOPp->mkAscon_engine__DOT__rg_interface_2),128);
        tracep->fullWData(oldp+123,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_D_IN),128);
        tracep->fullBit(oldp+127,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_EN));
        tracep->fullWData(oldp+128,(vlTOPp->mkAscon_engine__DOT__rg_interface_3),128);
        tracep->fullWData(oldp+132,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_D_IN),128);
        tracep->fullBit(oldp+136,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_EN));
        tracep->fullQData(oldp+137,(vlTOPp->mkAscon_engine__DOT__rg_state_0),64);
        tracep->fullQData(oldp+139,(vlTOPp->mkAscon_engine__DOT__rg_state_0_D_IN),64);
        tracep->fullBit(oldp+141,(vlTOPp->mkAscon_engine__DOT__rg_state_0_EN));
        tracep->fullQData(oldp+142,(vlTOPp->mkAscon_engine__DOT__rg_state_1),64);
        tracep->fullQData(oldp+144,(vlTOPp->mkAscon_engine__DOT__rg_state_1_D_IN),64);
        tracep->fullBit(oldp+146,(vlTOPp->mkAscon_engine__DOT__rg_state_1_EN));
        tracep->fullQData(oldp+147,(vlTOPp->mkAscon_engine__DOT__rg_state_2),64);
        tracep->fullQData(oldp+149,(vlTOPp->mkAscon_engine__DOT__rg_state_2_D_IN),64);
        tracep->fullBit(oldp+151,(vlTOPp->mkAscon_engine__DOT__rg_state_2_EN));
        tracep->fullQData(oldp+152,(vlTOPp->mkAscon_engine__DOT__rg_state_3),64);
        tracep->fullQData(oldp+154,(vlTOPp->mkAscon_engine__DOT__rg_state_3_D_IN),64);
        tracep->fullBit(oldp+156,(vlTOPp->mkAscon_engine__DOT__rg_state_3_EN));
        tracep->fullQData(oldp+157,(vlTOPp->mkAscon_engine__DOT__rg_state_4),64);
        tracep->fullQData(oldp+159,(vlTOPp->mkAscon_engine__DOT__rg_state_4_D_IN),64);
        tracep->fullBit(oldp+161,(vlTOPp->mkAscon_engine__DOT__rg_state_4_EN));
        tracep->fullBit(oldp+162,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+163,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+164,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+165,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+166,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+167,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_encrypted_data_state));
        tracep->fullBit(oldp+168,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_input_function));
        tracep->fullBit(oldp+169,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+170,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+171,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+172,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+173,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+174,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_encrypted_data_state));
        tracep->fullBit(oldp+175,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_input_function));
        tracep->fullQData(oldp+176,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+178,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+180,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+182,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+184,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+186,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+188,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+190,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+192,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+194,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+196,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+198,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+200,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+202,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+204,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_1),64);
        tracep->fullQData(oldp+206,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+208,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+210,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_6),64);
        tracep->fullQData(oldp+212,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+214,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+216,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+218,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_6),64);
        tracep->fullCData(oldp+220,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_2),4);
        tracep->fullCData(oldp+221,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_4),4);
        tracep->fullCData(oldp+222,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_5),4);
        tracep->fullBit(oldp+223,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_1));
        tracep->fullBit(oldp+224,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_2));
        tracep->fullBit(oldp+225,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_3));
        tracep->fullBit(oldp+226,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_2));
        tracep->fullBit(oldp+227,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_3));
        tracep->fullBit(oldp+228,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_4));
        tracep->fullBit(oldp+229,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_5));
        tracep->fullBit(oldp+230,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_6));
        tracep->fullBit(oldp+231,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_7));
        tracep->fullBit(oldp+232,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FSEL_2));
        tracep->fullQData(oldp+233,(vlTOPp->mkAscon_engine__DOT__y___05Fh18100),64);
        tracep->fullQData(oldp+235,(vlTOPp->mkAscon_engine__DOT__y___05Fh23211),64);
        tracep->fullWData(oldp+237,(vlTOPp->mkAscon_engine__DOT__lv_finalized_key___05Fh22041),320);
        tracep->fullWData(oldp+247,(vlTOPp->mkAscon_engine__DOT__lv_updated_finalized_data___05Fh22007),320);
        tracep->fullWData(oldp+257,(vlTOPp->mkAscon_engine__DOT__packed_pre_finalized_data___05Fh21335),320);
        tracep->fullWData(oldp+267,(vlTOPp->mkAscon_engine__DOT__padded_key___05Fh1252),320);
        tracep->fullWData(oldp+277,(vlTOPp->mkAscon_engine__DOT__rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___05F_d49),320);
        tracep->fullQData(oldp+287,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___05F_d33),64);
        tracep->fullQData(oldp+289,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___05F_d15),64);
        tracep->fullQData(oldp+291,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d23),64);
        tracep->fullQData(oldp+293,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d27),64);
        tracep->fullQData(oldp+295,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___05F_d19),64);
        tracep->fullQData(oldp+297,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d102),64);
        tracep->fullQData(oldp+299,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d108),64);
        tracep->fullQData(oldp+301,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d11),64);
        tracep->fullQData(oldp+303,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d116),64);
        tracep->fullQData(oldp+305,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d37),64);
        tracep->fullQData(oldp+307,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d45),64);
        tracep->fullQData(oldp+309,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d61),64);
        tracep->fullQData(oldp+311,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d69),64);
        tracep->fullQData(oldp+313,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d94),64);
        tracep->fullQData(oldp+315,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d76),64);
        tracep->fullQData(oldp+317,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d84),64);
        tracep->fullQData(oldp+319,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d181),64);
        tracep->fullQData(oldp+321,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d189),64);
        tracep->fullQData(oldp+323,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d278),64);
        tracep->fullQData(oldp+325,(vlTOPp->mkAscon_engine__DOT__din___05Fh10413),64);
        tracep->fullQData(oldp+327,(vlTOPp->mkAscon_engine__DOT__encryption0___05Fh16082),64);
        tracep->fullQData(oldp+329,(vlTOPp->mkAscon_engine__DOT__encryption1___05Fh16083),64);
        tracep->fullQData(oldp+331,(vlTOPp->mkAscon_engine__DOT__encryption_tag0___05Fh26646),64);
        tracep->fullQData(oldp+333,(vlTOPp->mkAscon_engine__DOT__encryption_tag1___05Fh26647),64);
        tracep->fullQData(oldp+335,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d136),64);
        tracep->fullQData(oldp+337,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d260),64);
        tracep->fullQData(oldp+339,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d198),64);
        tracep->fullQData(oldp+341,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d206),64);
        tracep->fullQData(oldp+343,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d281),64);
        tracep->fullQData(oldp+345,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d143),64);
        tracep->fullQData(oldp+347,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d151),64);
        tracep->fullQData(oldp+349,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d219),64);
        tracep->fullQData(oldp+351,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d266),64);
        tracep->fullQData(oldp+353,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d165),64);
        tracep->fullQData(oldp+355,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d173),64);
        tracep->fullQData(oldp+357,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d275),64);
        tracep->fullQData(oldp+359,(vlTOPp->mkAscon_engine__DOT__x___05Fh11626),64);
        tracep->fullQData(oldp+361,(vlTOPp->mkAscon_engine__DOT__x___05Fh15826),64);
        tracep->fullQData(oldp+363,(vlTOPp->mkAscon_engine__DOT__x___05Fh16020),64);
        tracep->fullQData(oldp+365,(vlTOPp->mkAscon_engine__DOT__x___05Fh18966),64);
        tracep->fullQData(oldp+367,(vlTOPp->mkAscon_engine__DOT__x___05Fh18968),64);
        tracep->fullQData(oldp+369,(vlTOPp->mkAscon_engine__DOT__x___05Fh18970),64);
        tracep->fullQData(oldp+371,(vlTOPp->mkAscon_engine__DOT__x___05Fh18972),64);
        tracep->fullQData(oldp+373,(vlTOPp->mkAscon_engine__DOT__x___05Fh19093),64);
        tracep->fullQData(oldp+375,(vlTOPp->mkAscon_engine__DOT__x___05Fh19095),64);
        tracep->fullQData(oldp+377,(vlTOPp->mkAscon_engine__DOT__x___05Fh19097),64);
        tracep->fullQData(oldp+379,(vlTOPp->mkAscon_engine__DOT__x___05Fh19099),64);
        tracep->fullQData(oldp+381,(vlTOPp->mkAscon_engine__DOT__x___05Fh19101),64);
        tracep->fullQData(oldp+383,(vlTOPp->mkAscon_engine__DOT__x___05Fh19103),64);
        tracep->fullQData(oldp+385,(vlTOPp->mkAscon_engine__DOT__x___05Fh19233),64);
        tracep->fullQData(oldp+387,(vlTOPp->mkAscon_engine__DOT__x___05Fh19307),64);
        tracep->fullQData(oldp+389,(vlTOPp->mkAscon_engine__DOT__x___05Fh19309),64);
        tracep->fullQData(oldp+391,(vlTOPp->mkAscon_engine__DOT__x___05Fh19643),64);
        tracep->fullQData(oldp+393,(vlTOPp->mkAscon_engine__DOT__x___05Fh19884),64);
        tracep->fullQData(oldp+395,(vlTOPp->mkAscon_engine__DOT__x___05Fh20125),64);
        tracep->fullQData(oldp+397,(vlTOPp->mkAscon_engine__DOT__x___05Fh20366),64);
        tracep->fullQData(oldp+399,(vlTOPp->mkAscon_engine__DOT__x___05Fh24077),64);
        tracep->fullQData(oldp+401,(vlTOPp->mkAscon_engine__DOT__x___05Fh24079),64);
        tracep->fullQData(oldp+403,(vlTOPp->mkAscon_engine__DOT__x___05Fh24081),64);
        tracep->fullQData(oldp+405,(vlTOPp->mkAscon_engine__DOT__x___05Fh24083),64);
        tracep->fullQData(oldp+407,(vlTOPp->mkAscon_engine__DOT__x___05Fh24085),64);
        tracep->fullQData(oldp+409,(vlTOPp->mkAscon_engine__DOT__x___05Fh24204),64);
        tracep->fullQData(oldp+411,(vlTOPp->mkAscon_engine__DOT__x___05Fh24206),64);
        tracep->fullQData(oldp+413,(vlTOPp->mkAscon_engine__DOT__x___05Fh24208),64);
        tracep->fullQData(oldp+415,(vlTOPp->mkAscon_engine__DOT__x___05Fh24210),64);
        tracep->fullQData(oldp+417,(vlTOPp->mkAscon_engine__DOT__x___05Fh24212),64);
        tracep->fullQData(oldp+419,(vlTOPp->mkAscon_engine__DOT__x___05Fh24214),64);
        tracep->fullQData(oldp+421,(vlTOPp->mkAscon_engine__DOT__x___05Fh24344),64);
        tracep->fullQData(oldp+423,(vlTOPp->mkAscon_engine__DOT__x___05Fh24346),64);
        tracep->fullQData(oldp+425,(vlTOPp->mkAscon_engine__DOT__x___05Fh24348),64);
        tracep->fullQData(oldp+427,(vlTOPp->mkAscon_engine__DOT__x___05Fh24418),64);
        tracep->fullQData(oldp+429,(vlTOPp->mkAscon_engine__DOT__x___05Fh24420),64);
        tracep->fullQData(oldp+431,(vlTOPp->mkAscon_engine__DOT__x___05Fh24422),64);
        tracep->fullQData(oldp+433,(vlTOPp->mkAscon_engine__DOT__x___05Fh24424),64);
        tracep->fullQData(oldp+435,(vlTOPp->mkAscon_engine__DOT__x___05Fh24426),64);
        tracep->fullQData(oldp+437,(vlTOPp->mkAscon_engine__DOT__x___05Fh24428),64);
        tracep->fullQData(oldp+439,(vlTOPp->mkAscon_engine__DOT__x___05Fh24534),64);
        tracep->fullQData(oldp+441,(vlTOPp->mkAscon_engine__DOT__x___05Fh24536),64);
        tracep->fullQData(oldp+443,(vlTOPp->mkAscon_engine__DOT__x___05Fh24538),64);
        tracep->fullQData(oldp+445,(vlTOPp->mkAscon_engine__DOT__x___05Fh24540),64);
        tracep->fullQData(oldp+447,(vlTOPp->mkAscon_engine__DOT__x___05Fh24754),64);
        tracep->fullQData(oldp+449,(vlTOPp->mkAscon_engine__DOT__x___05Fh24995),64);
        tracep->fullQData(oldp+451,(vlTOPp->mkAscon_engine__DOT__x___05Fh25236),64);
        tracep->fullQData(oldp+453,(vlTOPp->mkAscon_engine__DOT__x___05Fh25477),64);
        tracep->fullQData(oldp+455,(vlTOPp->mkAscon_engine__DOT__x___05Fh25718),64);
        tracep->fullQData(oldp+457,(vlTOPp->mkAscon_engine__DOT__x___05Fh25720),64);
        tracep->fullQData(oldp+459,(vlTOPp->mkAscon_engine__DOT__x___05Fh4174),64);
        tracep->fullQData(oldp+461,(vlTOPp->mkAscon_engine__DOT__x___05Fh4176),64);
        tracep->fullQData(oldp+463,(vlTOPp->mkAscon_engine__DOT__x___05Fh4178),64);
        tracep->fullQData(oldp+465,(vlTOPp->mkAscon_engine__DOT__x___05Fh4180),64);
        tracep->fullQData(oldp+467,(vlTOPp->mkAscon_engine__DOT__x___05Fh4182),64);
        tracep->fullQData(oldp+469,(vlTOPp->mkAscon_engine__DOT__x___05Fh4184),64);
        tracep->fullQData(oldp+471,(vlTOPp->mkAscon_engine__DOT__x___05Fh4301),64);
        tracep->fullQData(oldp+473,(vlTOPp->mkAscon_engine__DOT__x___05Fh4303),64);
        tracep->fullQData(oldp+475,(vlTOPp->mkAscon_engine__DOT__x___05Fh4305),64);
        tracep->fullQData(oldp+477,(vlTOPp->mkAscon_engine__DOT__x___05Fh4307),64);
        tracep->fullQData(oldp+479,(vlTOPp->mkAscon_engine__DOT__x___05Fh4309),64);
        tracep->fullQData(oldp+481,(vlTOPp->mkAscon_engine__DOT__x___05Fh4311),64);
        tracep->fullQData(oldp+483,(vlTOPp->mkAscon_engine__DOT__x___05Fh4441),64);
        tracep->fullQData(oldp+485,(vlTOPp->mkAscon_engine__DOT__x___05Fh4443),64);
        tracep->fullQData(oldp+487,(vlTOPp->mkAscon_engine__DOT__x___05Fh4445),64);
        tracep->fullQData(oldp+489,(vlTOPp->mkAscon_engine__DOT__x___05Fh4515),64);
        tracep->fullQData(oldp+491,(vlTOPp->mkAscon_engine__DOT__x___05Fh4517),64);
        tracep->fullQData(oldp+493,(vlTOPp->mkAscon_engine__DOT__x___05Fh4519),64);
        tracep->fullQData(oldp+495,(vlTOPp->mkAscon_engine__DOT__x___05Fh4521),64);
        tracep->fullQData(oldp+497,(vlTOPp->mkAscon_engine__DOT__x___05Fh4523),64);
        tracep->fullQData(oldp+499,(vlTOPp->mkAscon_engine__DOT__x___05Fh4525),64);
        tracep->fullQData(oldp+501,(vlTOPp->mkAscon_engine__DOT__x___05Fh4631),64);
        tracep->fullQData(oldp+503,(vlTOPp->mkAscon_engine__DOT__x___05Fh4633),64);
        tracep->fullQData(oldp+505,(vlTOPp->mkAscon_engine__DOT__x___05Fh4635),64);
        tracep->fullQData(oldp+507,(vlTOPp->mkAscon_engine__DOT__x___05Fh4851),64);
        tracep->fullQData(oldp+509,(vlTOPp->mkAscon_engine__DOT__x___05Fh5092),64);
        tracep->fullQData(oldp+511,(vlTOPp->mkAscon_engine__DOT__x___05Fh5333),64);
        tracep->fullQData(oldp+513,(vlTOPp->mkAscon_engine__DOT__x___05Fh5574),64);
        tracep->fullQData(oldp+515,(vlTOPp->mkAscon_engine__DOT__x___05Fh5815),64);
        tracep->fullQData(oldp+517,(vlTOPp->mkAscon_engine__DOT__x___05Fh7099),64);
        tracep->fullQData(oldp+519,(vlTOPp->mkAscon_engine__DOT__y___05Fh18975),64);
        tracep->fullQData(oldp+521,(vlTOPp->mkAscon_engine__DOT__y___05Fh19098),64);
        tracep->fullQData(oldp+523,(vlTOPp->mkAscon_engine__DOT__y___05Fh19106),64);
        tracep->fullQData(oldp+525,(vlTOPp->mkAscon_engine__DOT__y___05Fh19644),64);
        tracep->fullQData(oldp+527,(vlTOPp->mkAscon_engine__DOT__y___05Fh19646),64);
        tracep->fullQData(oldp+529,(vlTOPp->mkAscon_engine__DOT__y___05Fh19885),64);
        tracep->fullQData(oldp+531,(vlTOPp->mkAscon_engine__DOT__y___05Fh19887),64);
        tracep->fullQData(oldp+533,(vlTOPp->mkAscon_engine__DOT__y___05Fh20126),64);
        tracep->fullQData(oldp+535,(vlTOPp->mkAscon_engine__DOT__y___05Fh20128),64);
        tracep->fullQData(oldp+537,(vlTOPp->mkAscon_engine__DOT__y___05Fh20367),64);
        tracep->fullQData(oldp+539,(vlTOPp->mkAscon_engine__DOT__y___05Fh20369),64);
        tracep->fullQData(oldp+541,(vlTOPp->mkAscon_engine__DOT__y___05Fh24086),64);
        tracep->fullQData(oldp+543,(vlTOPp->mkAscon_engine__DOT__y___05Fh24209),64);
        tracep->fullQData(oldp+545,(vlTOPp->mkAscon_engine__DOT__y___05Fh24213),64);
        tracep->fullQData(oldp+547,(vlTOPp->mkAscon_engine__DOT__y___05Fh24217),64);
        tracep->fullQData(oldp+549,(vlTOPp->mkAscon_engine__DOT__y___05Fh24429),64);
        tracep->fullQData(oldp+551,(vlTOPp->mkAscon_engine__DOT__y___05Fh24537),64);
        tracep->fullQData(oldp+553,(vlTOPp->mkAscon_engine__DOT__y___05Fh24755),64);
        tracep->fullQData(oldp+555,(vlTOPp->mkAscon_engine__DOT__y___05Fh24757),64);
        tracep->fullQData(oldp+557,(vlTOPp->mkAscon_engine__DOT__y___05Fh24996),64);
        tracep->fullQData(oldp+559,(vlTOPp->mkAscon_engine__DOT__y___05Fh24998),64);
        tracep->fullQData(oldp+561,(vlTOPp->mkAscon_engine__DOT__y___05Fh25237),64);
        tracep->fullQData(oldp+563,(vlTOPp->mkAscon_engine__DOT__y___05Fh25239),64);
        tracep->fullQData(oldp+565,(vlTOPp->mkAscon_engine__DOT__y___05Fh25478),64);
        tracep->fullQData(oldp+567,(vlTOPp->mkAscon_engine__DOT__y___05Fh25480),64);
        tracep->fullQData(oldp+569,(vlTOPp->mkAscon_engine__DOT__y___05Fh25719),64);
        tracep->fullQData(oldp+571,(vlTOPp->mkAscon_engine__DOT__y___05Fh25721),64);
        tracep->fullQData(oldp+573,(vlTOPp->mkAscon_engine__DOT__y___05Fh4179),64);
        tracep->fullQData(oldp+575,(vlTOPp->mkAscon_engine__DOT__y___05Fh4183),64);
        tracep->fullQData(oldp+577,(vlTOPp->mkAscon_engine__DOT__y___05Fh4306),64);
        tracep->fullQData(oldp+579,(vlTOPp->mkAscon_engine__DOT__y___05Fh4310),64);
        tracep->fullQData(oldp+581,(vlTOPp->mkAscon_engine__DOT__y___05Fh4314),64);
        tracep->fullQData(oldp+583,(vlTOPp->mkAscon_engine__DOT__y___05Fh4526),64);
        tracep->fullQData(oldp+585,(vlTOPp->mkAscon_engine__DOT__y___05Fh4852),64);
        tracep->fullQData(oldp+587,(vlTOPp->mkAscon_engine__DOT__y___05Fh4854),64);
        tracep->fullQData(oldp+589,(vlTOPp->mkAscon_engine__DOT__y___05Fh5093),64);
        tracep->fullQData(oldp+591,(vlTOPp->mkAscon_engine__DOT__y___05Fh5095),64);
        tracep->fullQData(oldp+593,(vlTOPp->mkAscon_engine__DOT__y___05Fh5334),64);
        tracep->fullQData(oldp+595,(vlTOPp->mkAscon_engine__DOT__y___05Fh5336),64);
        tracep->fullQData(oldp+597,(vlTOPp->mkAscon_engine__DOT__y___05Fh5575),64);
        tracep->fullQData(oldp+599,(vlTOPp->mkAscon_engine__DOT__y___05Fh5577),64);
        tracep->fullQData(oldp+601,(vlTOPp->mkAscon_engine__DOT__y___05Fh5816),64);
        tracep->fullQData(oldp+603,(vlTOPp->mkAscon_engine__DOT__y___05Fh5818),64);
        tracep->fullCData(oldp+605,(vlTOPp->mkAscon_engine__DOT__x___05Fh18116),4);
        tracep->fullCData(oldp+606,(vlTOPp->mkAscon_engine__DOT__x___05Fh23227),4);
        tracep->fullCData(oldp+607,(vlTOPp->mkAscon_engine__DOT__x___05Fh26558),4);
        tracep->fullBit(oldp+608,(vlTOPp->mkAscon_engine__DOT__counter_ULT_12___05F_d4));
    }
}
