// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__Syms.h"
#include "Vtop.h"



// FUNCTIONS
Vtop__Syms::Vtop__Syms(Vtop* topp, const char* namep)
    // Setup locals
    : __Vm_namep(namep)
    , __Vm_activity(false)
    , __Vm_baseCode(0)
    , __Vm_didInit(false)
    // Setup submodule names
{
    // Pointer to top level
    TOPp = topp;
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOPp->__Vconfigure(this, true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_mkAscon_engine.configure(this, name(), "mkAscon_engine", "mkAscon_engine", -9, VerilatedScope::SCOPE_MODULE);
    
    // Setup scope hierarchy
    __Vhier.add(0, &__Vscope_mkAscon_engine);
    
    // Setup export functions
    for (int __Vfinal=0; __Vfinal<2; __Vfinal++) {
        __Vscope_TOP.varInsert(__Vfinal,"CLK", &(TOPp->CLK), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"EN_input_function", &(TOPp->EN_input_function), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_ciphertext", &(TOPp->RDY_ciphertext), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_decrypted_data", &(TOPp->RDY_decrypted_data), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_decrypted_tag", &(TOPp->RDY_decrypted_tag), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_input_function", &(TOPp->RDY_input_function), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RDY_tag", &(TOPp->RDY_tag), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"RST_N", &(TOPp->RST_N), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ciphertext", &(TOPp->ciphertext), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"decrypted_data", &(TOPp->decrypted_data), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"decrypted_tag", &(TOPp->decrypted_tag), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"input_function_associated_data", &(TOPp->input_function_associated_data), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"input_function_key", &(TOPp->input_function_key), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"input_function_mode", &(TOPp->input_function_mode), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"input_function_nonce", &(TOPp->input_function_nonce), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"input_function_plaintext", &(TOPp->input_function_plaintext), false, VLVT_WDATA,VLVD_IN|VLVF_PUB_RW,1 ,127,0);
        __Vscope_TOP.varInsert(__Vfinal,"tag", &(TOPp->tag), false, VLVT_WDATA,VLVD_OUT|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_associated_data_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_associated_data_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_decryption_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_decryption_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_encryption_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_encryption_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_finalization_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_finalization_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_intialization_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_intialization_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_permutate_associated_data_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_associated_data_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_RL_permutate_encrypt_decrypt_state", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_encrypt_decrypt_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CAN_FIRE_input_function", &(TOPp->mkAscon_engine__DOT__CAN_FIRE_input_function), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"CLK", &(TOPp->mkAscon_engine__DOT__CLK), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"EN_input_function", &(TOPp->mkAscon_engine__DOT__EN_input_function), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___d33", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___05F_d33), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___d15", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___05F_d15), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d23", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d23), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d27", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d27), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___d19", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___05F_d19), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d102", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d102), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d108", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d108), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d11", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d11), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d116", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d116), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d37", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d37), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d45", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d45), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d61", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d61), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d69", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d69), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d94", &(TOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d94), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d76", &(TOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d76), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d84", &(TOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d84), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d181", &(TOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d181), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d189", &(TOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d189), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___d281", &(TOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_77_XOR_rg_st_ETC___05F_d281), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__SEL_1", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__SEL_2", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__SEL_3", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__VAL_2", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__VAL_4", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_counter_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_2", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_3", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_4", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_5", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_6", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_7", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__SEL_8", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_fsm_state_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FVAL_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__SEL_2", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FSEL_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__VAL_1", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__VAL_3", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_3), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__VAL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_4), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_0_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_1_write_1__VAL_1", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_1_write_1__VAL_3", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_3), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_1_write_1__VAL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_4), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_1_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_1_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__PSEL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FPSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__SEL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__VAL_1", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__VAL_2", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_2_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_3_write_1__SEL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_3_write_1__VAL_1", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_3_write_1__VAL_2", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_3_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_3_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_4_write_1__SEL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FSEL_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_4_write_1__VAL_2", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_4_write_1__VAL_4", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_4), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_4_write_1__VAL_5", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"MUX_rg_state_4_write_1__VAL_6", &(TOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RDY_ciphertext", &(TOPp->mkAscon_engine__DOT__RDY_ciphertext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RDY_decrypted_data", &(TOPp->mkAscon_engine__DOT__RDY_decrypted_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RDY_decrypted_tag", &(TOPp->mkAscon_engine__DOT__RDY_decrypted_tag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RDY_input_function", &(TOPp->mkAscon_engine__DOT__RDY_input_function), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RDY_tag", &(TOPp->mkAscon_engine__DOT__RDY_tag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"RST_N", &(TOPp->mkAscon_engine__DOT__RST_N), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_associated_data_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_associated_data_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_decryption_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_decryption_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_encryption_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_encryption_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_finalization_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_finalization_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_intialization_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_intialization_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_permutate_associated_data_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_associated_data_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_RL_permutate_encrypt_decrypt_state", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_encrypt_decrypt_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"WILL_FIRE_input_function", &(TOPp->mkAscon_engine__DOT__WILL_FIRE_input_function), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"_0b0_CONCAT_rg_interface_0_2_CONCAT_0b0_47_XOR__ETC___d251", &(TOPp->mkAscon_engine__DOT___0b0_CONCAT_rg_interface_0_2_CONCAT_0b0_47_XOR___05FETC___05F_d251), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ciphertext", &(TOPp->mkAscon_engine__DOT__ciphertext), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"counter", &(TOPp->mkAscon_engine__DOT__counter), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"counter_D_IN", &(TOPp->mkAscon_engine__DOT__counter_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"counter_EN", &(TOPp->mkAscon_engine__DOT__counter_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"counter_ULT_12___d4", &(TOPp->mkAscon_engine__DOT__counter_ULT_12___05F_d4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"decrypted_data", &(TOPp->mkAscon_engine__DOT__decrypted_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"decrypted_tag", &(TOPp->mkAscon_engine__DOT__decrypted_tag), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"din__h10845", &(TOPp->mkAscon_engine__DOT__din___05Fh10845), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"encryption0__h16560", &(TOPp->mkAscon_engine__DOT__encryption0___05Fh16560), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"encryption1__h16561", &(TOPp->mkAscon_engine__DOT__encryption1___05Fh16561), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"encryption_tag0__h29252", &(TOPp->mkAscon_engine__DOT__encryption_tag0___05Fh29252), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"encryption_tag1__h29253", &(TOPp->mkAscon_engine__DOT__encryption_tag1___05Fh29253), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"fsm_state", &(TOPp->mkAscon_engine__DOT__fsm_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"fsm_state_D_IN", &(TOPp->mkAscon_engine__DOT__fsm_state_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"fsm_state_EN", &(TOPp->mkAscon_engine__DOT__fsm_state_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"input_function_associated_data", &(TOPp->mkAscon_engine__DOT__input_function_associated_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"input_function_key", &(TOPp->mkAscon_engine__DOT__input_function_key), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"input_function_mode", &(TOPp->mkAscon_engine__DOT__input_function_mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"input_function_nonce", &(TOPp->mkAscon_engine__DOT__input_function_nonce), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"input_function_plaintext", &(TOPp->mkAscon_engine__DOT__input_function_plaintext), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"iv_constant", &(TOPp->mkAscon_engine__DOT__iv_constant), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"iv_constant_D_IN", &(TOPp->mkAscon_engine__DOT__iv_constant_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"iv_constant_EN", &(TOPp->mkAscon_engine__DOT__iv_constant_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"lv_finalized_key__h24489", &(TOPp->mkAscon_engine__DOT__lv_finalized_key___05Fh24489), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"lv_updated_finalized_data__h24455", &(TOPp->mkAscon_engine__DOT__lv_updated_finalized_data___05Fh24455), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"packed_pre_finalized_data__h23783", &(TOPp->mkAscon_engine__DOT__packed_pre_finalized_data___05Fh23783), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"padded_key__h1678", &(TOPp->mkAscon_engine__DOT__padded_key___05Fh1678), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_ciphertext", &(TOPp->mkAscon_engine__DOT__ready_ciphertext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_ciphertext_D_IN", &(TOPp->mkAscon_engine__DOT__ready_ciphertext_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_ciphertext_EN", &(TOPp->mkAscon_engine__DOT__ready_ciphertext_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_data", &(TOPp->mkAscon_engine__DOT__ready_decrypted_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_data_D_IN", &(TOPp->mkAscon_engine__DOT__ready_decrypted_data_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_data_EN", &(TOPp->mkAscon_engine__DOT__ready_decrypted_data_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_tag", &(TOPp->mkAscon_engine__DOT__ready_decrypted_tag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_tag_D_IN", &(TOPp->mkAscon_engine__DOT__ready_decrypted_tag_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_decrypted_tag_EN", &(TOPp->mkAscon_engine__DOT__ready_decrypted_tag_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_tag", &(TOPp->mkAscon_engine__DOT__ready_tag), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_tag_D_IN", &(TOPp->mkAscon_engine__DOT__ready_tag_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"ready_tag_EN", &(TOPp->mkAscon_engine__DOT__ready_tag_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"req_associated_data", &(TOPp->mkAscon_engine__DOT__req_associated_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"req_associated_data_D_IN", &(TOPp->mkAscon_engine__DOT__req_associated_data_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"req_associated_data_EN", &(TOPp->mkAscon_engine__DOT__req_associated_data_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_0", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_0_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_0_EN", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_1", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_1_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decrypted_data_1_EN", &(TOPp->mkAscon_engine__DOT__rg_decrypted_data_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_0", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_0_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_0_EN", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_1", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_1_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_decryption_tag_1_EN", &(TOPp->mkAscon_engine__DOT__rg_decryption_tag_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_0", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_0_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_0_EN", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_1", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_1_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encrypted_data_1_EN", &(TOPp->mkAscon_engine__DOT__rg_encrypted_data_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_0", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_0_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_0_EN", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_1", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_1_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_encryption_tag_1_EN", &(TOPp->mkAscon_engine__DOT__rg_encryption_tag_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_0", &(TOPp->mkAscon_engine__DOT__rg_interface_0), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_interface_0_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_0_EN", &(TOPp->mkAscon_engine__DOT__rg_interface_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_1", &(TOPp->mkAscon_engine__DOT__rg_interface_1), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_interface_1_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_1_EN", &(TOPp->mkAscon_engine__DOT__rg_interface_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_2", &(TOPp->mkAscon_engine__DOT__rg_interface_2), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_2_D_IN", &(TOPp->mkAscon_engine__DOT__rg_interface_2_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_2_EN", &(TOPp->mkAscon_engine__DOT__rg_interface_2_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_3", &(TOPp->mkAscon_engine__DOT__rg_interface_3), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_3_D_IN", &(TOPp->mkAscon_engine__DOT__rg_interface_3_D_IN), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_interface_3_EN", &(TOPp->mkAscon_engine__DOT__rg_interface_3_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_0", &(TOPp->mkAscon_engine__DOT__rg_state_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___d49", &(TOPp->mkAscon_engine__DOT__rg_state_0_2_CONCAT_rg_state_1_4_CONCAT_rg_sta_ETC___05F_d49), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,319,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_0_D_IN", &(TOPp->mkAscon_engine__DOT__rg_state_0_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_0_EN", &(TOPp->mkAscon_engine__DOT__rg_state_0_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_1", &(TOPp->mkAscon_engine__DOT__rg_state_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_1_D_IN", &(TOPp->mkAscon_engine__DOT__rg_state_1_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_1_EN", &(TOPp->mkAscon_engine__DOT__rg_state_1_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_2", &(TOPp->mkAscon_engine__DOT__rg_state_2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d136", &(TOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d136), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d263", &(TOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d263), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_2_D_IN", &(TOPp->mkAscon_engine__DOT__rg_state_2_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_2_EN", &(TOPp->mkAscon_engine__DOT__rg_state_2_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_3", &(TOPp->mkAscon_engine__DOT__rg_state_3), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_3_D_IN", &(TOPp->mkAscon_engine__DOT__rg_state_3_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_3_EN", &(TOPp->mkAscon_engine__DOT__rg_state_3_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4", &(TOPp->mkAscon_engine__DOT__rg_state_4), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d198", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d198), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d206", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d206), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state__ETC___d284", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_91_XOR_rg_state___05FETC___05F_d284), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d143", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d143), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d151", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d151), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d219", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d219), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state__ETC___d269", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_32_XOR_rg_state___05FETC___05F_d269), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d165", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d165), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d173", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d173), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d278", &(TOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d278), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_D_IN", &(TOPp->mkAscon_engine__DOT__rg_state_4_D_IN), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"rg_state_4_EN", &(TOPp->mkAscon_engine__DOT__rg_state_4_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"select", &(TOPp->mkAscon_engine__DOT__select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"select_D_IN", &(TOPp->mkAscon_engine__DOT__select_D_IN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"select_EN", &(TOPp->mkAscon_engine__DOT__select_EN), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"tag", &(TOPp->mkAscon_engine__DOT__tag), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1 ,127,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h12058", &(TOPp->mkAscon_engine__DOT__x___05Fh12058), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h20564", &(TOPp->mkAscon_engine__DOT__x___05Fh20564), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21414", &(TOPp->mkAscon_engine__DOT__x___05Fh21414), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21416", &(TOPp->mkAscon_engine__DOT__x___05Fh21416), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21418", &(TOPp->mkAscon_engine__DOT__x___05Fh21418), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21420", &(TOPp->mkAscon_engine__DOT__x___05Fh21420), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21541", &(TOPp->mkAscon_engine__DOT__x___05Fh21541), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21543", &(TOPp->mkAscon_engine__DOT__x___05Fh21543), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21545", &(TOPp->mkAscon_engine__DOT__x___05Fh21545), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21547", &(TOPp->mkAscon_engine__DOT__x___05Fh21547), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21549", &(TOPp->mkAscon_engine__DOT__x___05Fh21549), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21551", &(TOPp->mkAscon_engine__DOT__x___05Fh21551), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21681", &(TOPp->mkAscon_engine__DOT__x___05Fh21681), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21755", &(TOPp->mkAscon_engine__DOT__x___05Fh21755), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h21757", &(TOPp->mkAscon_engine__DOT__x___05Fh21757), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h22091", &(TOPp->mkAscon_engine__DOT__x___05Fh22091), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h22332", &(TOPp->mkAscon_engine__DOT__x___05Fh22332), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h22573", &(TOPp->mkAscon_engine__DOT__x___05Fh22573), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h22814", &(TOPp->mkAscon_engine__DOT__x___05Fh22814), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h25687", &(TOPp->mkAscon_engine__DOT__x___05Fh25687), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26537", &(TOPp->mkAscon_engine__DOT__x___05Fh26537), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26539", &(TOPp->mkAscon_engine__DOT__x___05Fh26539), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26541", &(TOPp->mkAscon_engine__DOT__x___05Fh26541), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26543", &(TOPp->mkAscon_engine__DOT__x___05Fh26543), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26545", &(TOPp->mkAscon_engine__DOT__x___05Fh26545), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26664", &(TOPp->mkAscon_engine__DOT__x___05Fh26664), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26666", &(TOPp->mkAscon_engine__DOT__x___05Fh26666), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26668", &(TOPp->mkAscon_engine__DOT__x___05Fh26668), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26670", &(TOPp->mkAscon_engine__DOT__x___05Fh26670), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26672", &(TOPp->mkAscon_engine__DOT__x___05Fh26672), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26674", &(TOPp->mkAscon_engine__DOT__x___05Fh26674), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26804", &(TOPp->mkAscon_engine__DOT__x___05Fh26804), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26806", &(TOPp->mkAscon_engine__DOT__x___05Fh26806), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26808", &(TOPp->mkAscon_engine__DOT__x___05Fh26808), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26878", &(TOPp->mkAscon_engine__DOT__x___05Fh26878), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26880", &(TOPp->mkAscon_engine__DOT__x___05Fh26880), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26882", &(TOPp->mkAscon_engine__DOT__x___05Fh26882), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26884", &(TOPp->mkAscon_engine__DOT__x___05Fh26884), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26886", &(TOPp->mkAscon_engine__DOT__x___05Fh26886), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26888", &(TOPp->mkAscon_engine__DOT__x___05Fh26888), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26994", &(TOPp->mkAscon_engine__DOT__x___05Fh26994), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26996", &(TOPp->mkAscon_engine__DOT__x___05Fh26996), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h26998", &(TOPp->mkAscon_engine__DOT__x___05Fh26998), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h27000", &(TOPp->mkAscon_engine__DOT__x___05Fh27000), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h27214", &(TOPp->mkAscon_engine__DOT__x___05Fh27214), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h27455", &(TOPp->mkAscon_engine__DOT__x___05Fh27455), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h27696", &(TOPp->mkAscon_engine__DOT__x___05Fh27696), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h27937", &(TOPp->mkAscon_engine__DOT__x___05Fh27937), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h28178", &(TOPp->mkAscon_engine__DOT__x___05Fh28178), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h28180", &(TOPp->mkAscon_engine__DOT__x___05Fh28180), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h29164", &(TOPp->mkAscon_engine__DOT__x___05Fh29164), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4600", &(TOPp->mkAscon_engine__DOT__x___05Fh4600), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4602", &(TOPp->mkAscon_engine__DOT__x___05Fh4602), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4604", &(TOPp->mkAscon_engine__DOT__x___05Fh4604), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4606", &(TOPp->mkAscon_engine__DOT__x___05Fh4606), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4608", &(TOPp->mkAscon_engine__DOT__x___05Fh4608), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4610", &(TOPp->mkAscon_engine__DOT__x___05Fh4610), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4727", &(TOPp->mkAscon_engine__DOT__x___05Fh4727), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4729", &(TOPp->mkAscon_engine__DOT__x___05Fh4729), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4731", &(TOPp->mkAscon_engine__DOT__x___05Fh4731), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4733", &(TOPp->mkAscon_engine__DOT__x___05Fh4733), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4735", &(TOPp->mkAscon_engine__DOT__x___05Fh4735), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4737", &(TOPp->mkAscon_engine__DOT__x___05Fh4737), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4867", &(TOPp->mkAscon_engine__DOT__x___05Fh4867), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4869", &(TOPp->mkAscon_engine__DOT__x___05Fh4869), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4871", &(TOPp->mkAscon_engine__DOT__x___05Fh4871), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4941", &(TOPp->mkAscon_engine__DOT__x___05Fh4941), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4943", &(TOPp->mkAscon_engine__DOT__x___05Fh4943), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4945", &(TOPp->mkAscon_engine__DOT__x___05Fh4945), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4947", &(TOPp->mkAscon_engine__DOT__x___05Fh4947), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4949", &(TOPp->mkAscon_engine__DOT__x___05Fh4949), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h4951", &(TOPp->mkAscon_engine__DOT__x___05Fh4951), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5057", &(TOPp->mkAscon_engine__DOT__x___05Fh5057), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5059", &(TOPp->mkAscon_engine__DOT__x___05Fh5059), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5061", &(TOPp->mkAscon_engine__DOT__x___05Fh5061), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5277", &(TOPp->mkAscon_engine__DOT__x___05Fh5277), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5518", &(TOPp->mkAscon_engine__DOT__x___05Fh5518), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h5759", &(TOPp->mkAscon_engine__DOT__x___05Fh5759), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h6000", &(TOPp->mkAscon_engine__DOT__x___05Fh6000), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h6241", &(TOPp->mkAscon_engine__DOT__x___05Fh6241), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"x__h7531", &(TOPp->mkAscon_engine__DOT__x___05Fh7531), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h20548", &(TOPp->mkAscon_engine__DOT__y___05Fh20548), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h21423", &(TOPp->mkAscon_engine__DOT__y___05Fh21423), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h21546", &(TOPp->mkAscon_engine__DOT__y___05Fh21546), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h21554", &(TOPp->mkAscon_engine__DOT__y___05Fh21554), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22092", &(TOPp->mkAscon_engine__DOT__y___05Fh22092), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22094", &(TOPp->mkAscon_engine__DOT__y___05Fh22094), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22333", &(TOPp->mkAscon_engine__DOT__y___05Fh22333), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22335", &(TOPp->mkAscon_engine__DOT__y___05Fh22335), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22574", &(TOPp->mkAscon_engine__DOT__y___05Fh22574), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22576", &(TOPp->mkAscon_engine__DOT__y___05Fh22576), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22815", &(TOPp->mkAscon_engine__DOT__y___05Fh22815), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h22817", &(TOPp->mkAscon_engine__DOT__y___05Fh22817), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h25671", &(TOPp->mkAscon_engine__DOT__y___05Fh25671), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26546", &(TOPp->mkAscon_engine__DOT__y___05Fh26546), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26669", &(TOPp->mkAscon_engine__DOT__y___05Fh26669), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26673", &(TOPp->mkAscon_engine__DOT__y___05Fh26673), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26677", &(TOPp->mkAscon_engine__DOT__y___05Fh26677), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26889", &(TOPp->mkAscon_engine__DOT__y___05Fh26889), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h26997", &(TOPp->mkAscon_engine__DOT__y___05Fh26997), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27215", &(TOPp->mkAscon_engine__DOT__y___05Fh27215), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27217", &(TOPp->mkAscon_engine__DOT__y___05Fh27217), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27456", &(TOPp->mkAscon_engine__DOT__y___05Fh27456), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27458", &(TOPp->mkAscon_engine__DOT__y___05Fh27458), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27697", &(TOPp->mkAscon_engine__DOT__y___05Fh27697), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27699", &(TOPp->mkAscon_engine__DOT__y___05Fh27699), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27938", &(TOPp->mkAscon_engine__DOT__y___05Fh27938), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h27940", &(TOPp->mkAscon_engine__DOT__y___05Fh27940), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h28179", &(TOPp->mkAscon_engine__DOT__y___05Fh28179), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h28181", &(TOPp->mkAscon_engine__DOT__y___05Fh28181), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4605", &(TOPp->mkAscon_engine__DOT__y___05Fh4605), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4609", &(TOPp->mkAscon_engine__DOT__y___05Fh4609), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4732", &(TOPp->mkAscon_engine__DOT__y___05Fh4732), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4736", &(TOPp->mkAscon_engine__DOT__y___05Fh4736), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4740", &(TOPp->mkAscon_engine__DOT__y___05Fh4740), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h4952", &(TOPp->mkAscon_engine__DOT__y___05Fh4952), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5278", &(TOPp->mkAscon_engine__DOT__y___05Fh5278), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5280", &(TOPp->mkAscon_engine__DOT__y___05Fh5280), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5519", &(TOPp->mkAscon_engine__DOT__y___05Fh5519), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5521", &(TOPp->mkAscon_engine__DOT__y___05Fh5521), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5760", &(TOPp->mkAscon_engine__DOT__y___05Fh5760), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h5762", &(TOPp->mkAscon_engine__DOT__y___05Fh5762), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h6001", &(TOPp->mkAscon_engine__DOT__y___05Fh6001), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h6003", &(TOPp->mkAscon_engine__DOT__y___05Fh6003), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h6242", &(TOPp->mkAscon_engine__DOT__y___05Fh6242), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_mkAscon_engine.varInsert(__Vfinal,"y__h6244", &(TOPp->mkAscon_engine__DOT__y___05Fh6244), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
    }
}
