// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


//======================

void Vtop::trace(VerilatedFstC* tfp, int, int) {
    tfp->spTrace()->addInitCb(&traceInit, __VlSymsp);
    traceRegister(tfp->spTrace());
}

void Vtop::traceInit(void* userp, VerilatedFst* tracep, uint32_t code) {
    // Callback from tracep->open()
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    if (!Verilated::calcUnusedSigs()) {
        VL_FATAL_MT(__FILE__, __LINE__, __FILE__,
                        "Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.");
    }
    vlSymsp->__Vm_baseCode = code;
    tracep->module(vlSymsp->name());
    tracep->scopeEscape(' ');
    Vtop::traceInitTop(vlSymsp, tracep);
    tracep->scopeEscape('.');
}

//======================


void Vtop::traceInitTop(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceInitSub0(userp, tracep);
    }
}

void Vtop::traceInitSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    const int c = vlSymsp->__Vm_baseCode;
    if (false && tracep && c) {}  // Prevent unused
    // Body
    {
        tracep->declBit(c+1,"CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+2,"RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+3,"input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+7,"input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+11,"input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+15,"input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+19,"EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+20,"RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+21,"ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+25,"RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+26,"tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+30,"RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+31,"mkAscon_engine CLK",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+32,"mkAscon_engine RST_N",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+33,"mkAscon_engine input_function_plaintext",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+37,"mkAscon_engine input_function_associated_data",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+41,"mkAscon_engine input_function_key",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declArray(c+45,"mkAscon_engine input_function_nonce",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+49,"mkAscon_engine EN_input_function",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+50,"mkAscon_engine RDY_input_function",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+51,"mkAscon_engine ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+55,"mkAscon_engine RDY_ciphertext",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+56,"mkAscon_engine tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+60,"mkAscon_engine RDY_tag",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+61,"mkAscon_engine counter",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBus(c+62,"mkAscon_engine counter_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
        tracep->declBit(c+63,"mkAscon_engine counter_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBus(c+64,"mkAscon_engine fsm_state",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBus(c+65,"mkAscon_engine fsm_state_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
        tracep->declBit(c+66,"mkAscon_engine fsm_state_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+67,"mkAscon_engine iv_constant",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+69,"mkAscon_engine iv_constant_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+71,"mkAscon_engine iv_constant_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+72,"mkAscon_engine ready_ciphertext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+73,"mkAscon_engine ready_ciphertext_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+74,"mkAscon_engine ready_ciphertext_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+75,"mkAscon_engine ready_tag",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+76,"mkAscon_engine ready_tag_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+77,"mkAscon_engine ready_tag_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+78,"mkAscon_engine req_associated_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
        tracep->declBit(c+79,"mkAscon_engine req_associated_data_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+80,"mkAscon_engine req_associated_data_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+81,"mkAscon_engine rg_encrypted_data_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+83,"mkAscon_engine rg_encrypted_data_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+85,"mkAscon_engine rg_encrypted_data_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+86,"mkAscon_engine rg_encrypted_data_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+88,"mkAscon_engine rg_encrypted_data_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+90,"mkAscon_engine rg_encrypted_data_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+91,"mkAscon_engine rg_encryption_tag_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+93,"mkAscon_engine rg_encryption_tag_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+95,"mkAscon_engine rg_encryption_tag_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+96,"mkAscon_engine rg_encryption_tag_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+98,"mkAscon_engine rg_encryption_tag_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBit(c+100,"mkAscon_engine rg_encryption_tag_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+101,"mkAscon_engine rg_interface_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+105,"mkAscon_engine rg_interface_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+109,"mkAscon_engine rg_interface_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+110,"mkAscon_engine rg_interface_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+114,"mkAscon_engine rg_interface_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+118,"mkAscon_engine rg_interface_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+119,"mkAscon_engine rg_interface_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+123,"mkAscon_engine rg_interface_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+127,"mkAscon_engine rg_interface_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declArray(c+128,"mkAscon_engine rg_interface_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 127,0);
        tracep->declArray(c+132,"mkAscon_engine rg_interface_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declBit(c+136,"mkAscon_engine rg_interface_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+137,"mkAscon_engine rg_state_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+139,"mkAscon_engine rg_state_0_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+141,"mkAscon_engine rg_state_0_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+142,"mkAscon_engine rg_state_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+144,"mkAscon_engine rg_state_1_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+146,"mkAscon_engine rg_state_1_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+147,"mkAscon_engine rg_state_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+149,"mkAscon_engine rg_state_2_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+151,"mkAscon_engine rg_state_2_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+152,"mkAscon_engine rg_state_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+154,"mkAscon_engine rg_state_3_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+156,"mkAscon_engine rg_state_3_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+157,"mkAscon_engine rg_state_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+159,"mkAscon_engine rg_state_4_D_IN",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declBit(c+161,"mkAscon_engine rg_state_4_EN",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+162,"mkAscon_engine CAN_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+163,"mkAscon_engine CAN_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+164,"mkAscon_engine CAN_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+165,"mkAscon_engine CAN_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+166,"mkAscon_engine CAN_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+167,"mkAscon_engine CAN_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+168,"mkAscon_engine WILL_FIRE_RL_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+169,"mkAscon_engine WILL_FIRE_RL_encryption_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+170,"mkAscon_engine WILL_FIRE_RL_finalization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+171,"mkAscon_engine WILL_FIRE_RL_intialization_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+172,"mkAscon_engine WILL_FIRE_RL_permutate_associated_data_state",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+173,"mkAscon_engine WILL_FIRE_input_function",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+174,"mkAscon_engine MUX_rg_state_0_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+176,"mkAscon_engine MUX_rg_state_0_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+178,"mkAscon_engine MUX_rg_state_0_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+180,"mkAscon_engine MUX_rg_state_0_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+182,"mkAscon_engine MUX_rg_state_1_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+184,"mkAscon_engine MUX_rg_state_1_write_1__VAL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+186,"mkAscon_engine MUX_rg_state_1_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+188,"mkAscon_engine MUX_rg_state_1_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+190,"mkAscon_engine MUX_rg_state_2_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+192,"mkAscon_engine MUX_rg_state_2_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+194,"mkAscon_engine MUX_rg_state_2_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+196,"mkAscon_engine MUX_rg_state_3_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+198,"mkAscon_engine MUX_rg_state_3_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+200,"mkAscon_engine MUX_rg_state_3_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+202,"mkAscon_engine MUX_rg_state_4_write_1__VAL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+204,"mkAscon_engine MUX_rg_state_4_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+206,"mkAscon_engine MUX_counter_write_1__VAL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+207,"mkAscon_engine MUX_counter_write_1__VAL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+208,"mkAscon_engine MUX_counter_write_1__VAL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBit(c+209,"mkAscon_engine MUX_counter_write_1__SEL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+210,"mkAscon_engine MUX_counter_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+211,"mkAscon_engine MUX_fsm_state_write_1__SEL_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+212,"mkAscon_engine MUX_fsm_state_write_1__SEL_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+213,"mkAscon_engine MUX_fsm_state_write_1__SEL_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+214,"mkAscon_engine MUX_fsm_state_write_1__SEL_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+215,"mkAscon_engine MUX_fsm_state_write_1__SEL_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declBit(c+216,"mkAscon_engine MUX_rg_state_0_write_1__SEL_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
        tracep->declQuad(c+217,"mkAscon_engine y__h13356",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declQuad(c+219,"mkAscon_engine y__h19304",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 63,0);
        tracep->declArray(c+221,"mkAscon_engine intialization_output__h6775",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+231,"mkAscon_engine lv_updated_asso_data__h12195",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+241,"mkAscon_engine packed_associated_data__h11523",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+251,"mkAscon_engine padded_key__h6735",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+261,"mkAscon_engine padded_key_state__h16617",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+271,"mkAscon_engine pre_finalized_state__h17084",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 319,0);
        tracep->declArray(c+281,"mkAscon_engine rg_state_0_2_CONCAT_rg_state_1_4_6_XOR_rg_inte_ETC___d235",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 127,0);
        tracep->declQuad(c+285,"mkAscon_engine IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___d33",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+287,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___d15",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+289,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d23",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+291,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63__ETC___d27",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+293,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___d19",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+295,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d103",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+297,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d109",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+299,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d11",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+301,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d117",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+303,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d37",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+305,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d45",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+307,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d62",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+309,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d70",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+311,"mkAscon_engine IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___d95",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+313,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d77",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+315,"mkAscon_engine INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___d85",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+317,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___d183",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+319,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___d191",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+321,"mkAscon_engine INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___d269",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+323,"mkAscon_engine din__h12423",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+325,"mkAscon_engine encryption0__h16813",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+327,"mkAscon_engine encryption1__h16814",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+329,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d138",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+331,"mkAscon_engine rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___d251",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+333,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state__ETC___d200",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+335,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state__ETC___d208",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+337,"mkAscon_engine rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state__ETC___d272",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+339,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state__ETC___d145",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+341,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state__ETC___d153",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+343,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state__ETC___d221",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+345,"mkAscon_engine rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state__ETC___d257",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+347,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d167",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+349,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d175",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+351,"mkAscon_engine rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___d266",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+353,"mkAscon_engine x__h10893",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+355,"mkAscon_engine x__h10982",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+357,"mkAscon_engine x__h14222",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+359,"mkAscon_engine x__h14224",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+361,"mkAscon_engine x__h14226",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+363,"mkAscon_engine x__h14228",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+365,"mkAscon_engine x__h14349",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+367,"mkAscon_engine x__h14351",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+369,"mkAscon_engine x__h14353",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+371,"mkAscon_engine x__h14355",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+373,"mkAscon_engine x__h14357",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+375,"mkAscon_engine x__h14359",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+377,"mkAscon_engine x__h14489",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+379,"mkAscon_engine x__h14563",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+381,"mkAscon_engine x__h14565",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+383,"mkAscon_engine x__h14899",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+385,"mkAscon_engine x__h15140",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+387,"mkAscon_engine x__h15381",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+389,"mkAscon_engine x__h15622",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+391,"mkAscon_engine x__h20170",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+393,"mkAscon_engine x__h20172",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+395,"mkAscon_engine x__h20174",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+397,"mkAscon_engine x__h20176",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+399,"mkAscon_engine x__h20178",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+401,"mkAscon_engine x__h20297",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+403,"mkAscon_engine x__h20299",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+405,"mkAscon_engine x__h20301",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+407,"mkAscon_engine x__h20303",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+409,"mkAscon_engine x__h20305",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+411,"mkAscon_engine x__h20307",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+413,"mkAscon_engine x__h20437",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+415,"mkAscon_engine x__h20439",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+417,"mkAscon_engine x__h20441",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+419,"mkAscon_engine x__h20511",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+421,"mkAscon_engine x__h20513",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+423,"mkAscon_engine x__h20515",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+425,"mkAscon_engine x__h20517",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+427,"mkAscon_engine x__h20519",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+429,"mkAscon_engine x__h20521",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+431,"mkAscon_engine x__h20627",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+433,"mkAscon_engine x__h20629",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+435,"mkAscon_engine x__h20631",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+437,"mkAscon_engine x__h20633",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+439,"mkAscon_engine x__h20847",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+441,"mkAscon_engine x__h21088",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+443,"mkAscon_engine x__h21329",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+445,"mkAscon_engine x__h21570",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+447,"mkAscon_engine x__h21811",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+449,"mkAscon_engine x__h21813",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+451,"mkAscon_engine x__h3980",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+453,"mkAscon_engine x__h3982",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+455,"mkAscon_engine x__h3984",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+457,"mkAscon_engine x__h3986",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+459,"mkAscon_engine x__h3988",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+461,"mkAscon_engine x__h3990",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+463,"mkAscon_engine x__h4107",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+465,"mkAscon_engine x__h4109",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+467,"mkAscon_engine x__h4111",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+469,"mkAscon_engine x__h4113",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+471,"mkAscon_engine x__h4115",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+473,"mkAscon_engine x__h4117",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+475,"mkAscon_engine x__h4247",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+477,"mkAscon_engine x__h4249",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+479,"mkAscon_engine x__h4251",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+481,"mkAscon_engine x__h4321",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+483,"mkAscon_engine x__h4323",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+485,"mkAscon_engine x__h4325",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+487,"mkAscon_engine x__h4327",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+489,"mkAscon_engine x__h4329",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+491,"mkAscon_engine x__h4331",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+493,"mkAscon_engine x__h4437",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+495,"mkAscon_engine x__h4439",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+497,"mkAscon_engine x__h4441",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+499,"mkAscon_engine x__h4657",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+501,"mkAscon_engine x__h4898",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+503,"mkAscon_engine x__h5139",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+505,"mkAscon_engine x__h5380",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+507,"mkAscon_engine x__h5621",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+509,"mkAscon_engine y__h14231",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+511,"mkAscon_engine y__h14354",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+513,"mkAscon_engine y__h14362",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+515,"mkAscon_engine y__h14900",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+517,"mkAscon_engine y__h14902",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+519,"mkAscon_engine y__h15141",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+521,"mkAscon_engine y__h15143",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+523,"mkAscon_engine y__h15382",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+525,"mkAscon_engine y__h15384",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+527,"mkAscon_engine y__h15623",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+529,"mkAscon_engine y__h15625",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+531,"mkAscon_engine y__h20179",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+533,"mkAscon_engine y__h20302",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+535,"mkAscon_engine y__h20306",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+537,"mkAscon_engine y__h20310",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+539,"mkAscon_engine y__h20522",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+541,"mkAscon_engine y__h20630",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+543,"mkAscon_engine y__h20848",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+545,"mkAscon_engine y__h20850",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+547,"mkAscon_engine y__h21089",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+549,"mkAscon_engine y__h21091",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+551,"mkAscon_engine y__h21330",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+553,"mkAscon_engine y__h21332",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+555,"mkAscon_engine y__h21571",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+557,"mkAscon_engine y__h21573",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+559,"mkAscon_engine y__h21812",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+561,"mkAscon_engine y__h21814",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+563,"mkAscon_engine y__h3985",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+565,"mkAscon_engine y__h3989",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+567,"mkAscon_engine y__h4112",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+569,"mkAscon_engine y__h4116",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+571,"mkAscon_engine y__h4120",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+573,"mkAscon_engine y__h4332",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+575,"mkAscon_engine y__h4658",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+577,"mkAscon_engine y__h4660",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+579,"mkAscon_engine y__h4899",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+581,"mkAscon_engine y__h4901",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+583,"mkAscon_engine y__h5140",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+585,"mkAscon_engine y__h5142",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+587,"mkAscon_engine y__h5381",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+589,"mkAscon_engine y__h5383",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+591,"mkAscon_engine y__h5622",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declQuad(c+593,"mkAscon_engine y__h5624",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 63,0);
        tracep->declBus(c+595,"mkAscon_engine x__h13372",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+596,"mkAscon_engine x__h19320",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBus(c+597,"mkAscon_engine x__h22665",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
        tracep->declBit(c+598,"mkAscon_engine counter_ULT_12___d4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    }
}

void Vtop::traceRegister(VerilatedFst* tracep) {
    // Body
    {
        tracep->addFullCb(&traceFullTop0, __VlSymsp);
        tracep->addChgCb(&traceChgTop0, __VlSymsp);
        tracep->addCleanupCb(&traceCleanup, __VlSymsp);
    }
}

void Vtop::traceFullTop0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    // Body
    {
        vlTOPp->traceFullSub0(userp, tracep);
    }
}

void Vtop::traceFullSub0(void* userp, VerilatedFst* tracep) {
    Vtop__Syms* __restrict vlSymsp = static_cast<Vtop__Syms*>(userp);
    Vtop* const __restrict vlTOPp VL_ATTR_UNUSED = vlSymsp->TOPp;
    vluint32_t* const oldp = tracep->oldp(vlSymsp->__Vm_baseCode);
    if (false && oldp) {}  // Prevent unused
    // Body
    {
        tracep->fullBit(oldp+1,(vlTOPp->CLK));
        tracep->fullBit(oldp+2,(vlTOPp->RST_N));
        tracep->fullWData(oldp+3,(vlTOPp->input_function_plaintext),128);
        tracep->fullWData(oldp+7,(vlTOPp->input_function_associated_data),128);
        tracep->fullWData(oldp+11,(vlTOPp->input_function_key),128);
        tracep->fullWData(oldp+15,(vlTOPp->input_function_nonce),128);
        tracep->fullBit(oldp+19,(vlTOPp->EN_input_function));
        tracep->fullBit(oldp+20,(vlTOPp->RDY_input_function));
        tracep->fullWData(oldp+21,(vlTOPp->ciphertext),128);
        tracep->fullBit(oldp+25,(vlTOPp->RDY_ciphertext));
        tracep->fullWData(oldp+26,(vlTOPp->tag),128);
        tracep->fullBit(oldp+30,(vlTOPp->RDY_tag));
        tracep->fullBit(oldp+31,(vlTOPp->mkAscon_engine__DOT__CLK));
        tracep->fullBit(oldp+32,(vlTOPp->mkAscon_engine__DOT__RST_N));
        tracep->fullWData(oldp+33,(vlTOPp->mkAscon_engine__DOT__input_function_plaintext),128);
        tracep->fullWData(oldp+37,(vlTOPp->mkAscon_engine__DOT__input_function_associated_data),128);
        tracep->fullWData(oldp+41,(vlTOPp->mkAscon_engine__DOT__input_function_key),128);
        tracep->fullWData(oldp+45,(vlTOPp->mkAscon_engine__DOT__input_function_nonce),128);
        tracep->fullBit(oldp+49,(vlTOPp->mkAscon_engine__DOT__EN_input_function));
        tracep->fullBit(oldp+50,(vlTOPp->mkAscon_engine__DOT__RDY_input_function));
        tracep->fullWData(oldp+51,(vlTOPp->mkAscon_engine__DOT__ciphertext),128);
        tracep->fullBit(oldp+55,(vlTOPp->mkAscon_engine__DOT__RDY_ciphertext));
        tracep->fullWData(oldp+56,(vlTOPp->mkAscon_engine__DOT__tag),128);
        tracep->fullBit(oldp+60,(vlTOPp->mkAscon_engine__DOT__RDY_tag));
        tracep->fullCData(oldp+61,(vlTOPp->mkAscon_engine__DOT__counter),4);
        tracep->fullCData(oldp+62,(vlTOPp->mkAscon_engine__DOT__counter_D_IN),4);
        tracep->fullBit(oldp+63,(vlTOPp->mkAscon_engine__DOT__counter_EN));
        tracep->fullCData(oldp+64,(vlTOPp->mkAscon_engine__DOT__fsm_state),3);
        tracep->fullCData(oldp+65,(vlTOPp->mkAscon_engine__DOT__fsm_state_D_IN),3);
        tracep->fullBit(oldp+66,(vlTOPp->mkAscon_engine__DOT__fsm_state_EN));
        tracep->fullQData(oldp+67,(vlTOPp->mkAscon_engine__DOT__iv_constant),64);
        tracep->fullQData(oldp+69,(vlTOPp->mkAscon_engine__DOT__iv_constant_D_IN),64);
        tracep->fullBit(oldp+71,(vlTOPp->mkAscon_engine__DOT__iv_constant_EN));
        tracep->fullBit(oldp+72,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext));
        tracep->fullBit(oldp+73,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_D_IN));
        tracep->fullBit(oldp+74,(vlTOPp->mkAscon_engine__DOT__ready_ciphertext_EN));
        tracep->fullBit(oldp+75,(vlTOPp->mkAscon_engine__DOT__ready_tag));
        tracep->fullBit(oldp+76,(vlTOPp->mkAscon_engine__DOT__ready_tag_D_IN));
        tracep->fullBit(oldp+77,(vlTOPp->mkAscon_engine__DOT__ready_tag_EN));
        tracep->fullBit(oldp+78,(vlTOPp->mkAscon_engine__DOT__req_associated_data));
        tracep->fullBit(oldp+79,(vlTOPp->mkAscon_engine__DOT__req_associated_data_D_IN));
        tracep->fullBit(oldp+80,(vlTOPp->mkAscon_engine__DOT__req_associated_data_EN));
        tracep->fullQData(oldp+81,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0),64);
        tracep->fullQData(oldp+83,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_D_IN),64);
        tracep->fullBit(oldp+85,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_0_EN));
        tracep->fullQData(oldp+86,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1),64);
        tracep->fullQData(oldp+88,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_D_IN),64);
        tracep->fullBit(oldp+90,(vlTOPp->mkAscon_engine__DOT__rg_encrypted_data_1_EN));
        tracep->fullQData(oldp+91,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0),64);
        tracep->fullQData(oldp+93,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_D_IN),64);
        tracep->fullBit(oldp+95,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_0_EN));
        tracep->fullQData(oldp+96,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1),64);
        tracep->fullQData(oldp+98,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_D_IN),64);
        tracep->fullBit(oldp+100,(vlTOPp->mkAscon_engine__DOT__rg_encryption_tag_1_EN));
        tracep->fullWData(oldp+101,(vlTOPp->mkAscon_engine__DOT__rg_interface_0),128);
        tracep->fullWData(oldp+105,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_D_IN),128);
        tracep->fullBit(oldp+109,(vlTOPp->mkAscon_engine__DOT__rg_interface_0_EN));
        tracep->fullWData(oldp+110,(vlTOPp->mkAscon_engine__DOT__rg_interface_1),128);
        tracep->fullWData(oldp+114,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_D_IN),128);
        tracep->fullBit(oldp+118,(vlTOPp->mkAscon_engine__DOT__rg_interface_1_EN));
        tracep->fullWData(oldp+119,(vlTOPp->mkAscon_engine__DOT__rg_interface_2),128);
        tracep->fullWData(oldp+123,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_D_IN),128);
        tracep->fullBit(oldp+127,(vlTOPp->mkAscon_engine__DOT__rg_interface_2_EN));
        tracep->fullWData(oldp+128,(vlTOPp->mkAscon_engine__DOT__rg_interface_3),128);
        tracep->fullWData(oldp+132,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_D_IN),128);
        tracep->fullBit(oldp+136,(vlTOPp->mkAscon_engine__DOT__rg_interface_3_EN));
        tracep->fullQData(oldp+137,(vlTOPp->mkAscon_engine__DOT__rg_state_0),64);
        tracep->fullQData(oldp+139,(vlTOPp->mkAscon_engine__DOT__rg_state_0_D_IN),64);
        tracep->fullBit(oldp+141,(vlTOPp->mkAscon_engine__DOT__rg_state_0_EN));
        tracep->fullQData(oldp+142,(vlTOPp->mkAscon_engine__DOT__rg_state_1),64);
        tracep->fullQData(oldp+144,(vlTOPp->mkAscon_engine__DOT__rg_state_1_D_IN),64);
        tracep->fullBit(oldp+146,(vlTOPp->mkAscon_engine__DOT__rg_state_1_EN));
        tracep->fullQData(oldp+147,(vlTOPp->mkAscon_engine__DOT__rg_state_2),64);
        tracep->fullQData(oldp+149,(vlTOPp->mkAscon_engine__DOT__rg_state_2_D_IN),64);
        tracep->fullBit(oldp+151,(vlTOPp->mkAscon_engine__DOT__rg_state_2_EN));
        tracep->fullQData(oldp+152,(vlTOPp->mkAscon_engine__DOT__rg_state_3),64);
        tracep->fullQData(oldp+154,(vlTOPp->mkAscon_engine__DOT__rg_state_3_D_IN),64);
        tracep->fullBit(oldp+156,(vlTOPp->mkAscon_engine__DOT__rg_state_3_EN));
        tracep->fullQData(oldp+157,(vlTOPp->mkAscon_engine__DOT__rg_state_4),64);
        tracep->fullQData(oldp+159,(vlTOPp->mkAscon_engine__DOT__rg_state_4_D_IN),64);
        tracep->fullBit(oldp+161,(vlTOPp->mkAscon_engine__DOT__rg_state_4_EN));
        tracep->fullBit(oldp+162,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+163,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+164,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+165,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+166,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+167,(vlTOPp->mkAscon_engine__DOT__CAN_FIRE_input_function));
        tracep->fullBit(oldp+168,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_associated_data_state));
        tracep->fullBit(oldp+169,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_encryption_state));
        tracep->fullBit(oldp+170,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_finalization_state));
        tracep->fullBit(oldp+171,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_intialization_state));
        tracep->fullBit(oldp+172,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_RL_permutate_associated_data_state));
        tracep->fullBit(oldp+173,(vlTOPp->mkAscon_engine__DOT__WILL_FIRE_input_function));
        tracep->fullQData(oldp+174,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+176,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+178,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+180,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+182,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+184,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_3),64);
        tracep->fullQData(oldp+186,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+188,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_1_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+190,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+192,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+194,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_2_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+196,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+198,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_4),64);
        tracep->fullQData(oldp+200,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_3_write_1___05FVAL_5),64);
        tracep->fullQData(oldp+202,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_2),64);
        tracep->fullQData(oldp+204,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_4_write_1___05FVAL_5),64);
        tracep->fullCData(oldp+206,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_1),4);
        tracep->fullCData(oldp+207,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_4),4);
        tracep->fullCData(oldp+208,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FVAL_5),4);
        tracep->fullBit(oldp+209,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_1));
        tracep->fullBit(oldp+210,(vlTOPp->mkAscon_engine__DOT__MUX_counter_write_1___05FSEL_2));
        tracep->fullBit(oldp+211,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_2));
        tracep->fullBit(oldp+212,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_3));
        tracep->fullBit(oldp+213,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_4));
        tracep->fullBit(oldp+214,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_5));
        tracep->fullBit(oldp+215,(vlTOPp->mkAscon_engine__DOT__MUX_fsm_state_write_1___05FSEL_6));
        tracep->fullBit(oldp+216,(vlTOPp->mkAscon_engine__DOT__MUX_rg_state_0_write_1___05FSEL_1));
        tracep->fullQData(oldp+217,(vlTOPp->mkAscon_engine__DOT__y___05Fh13356),64);
        tracep->fullQData(oldp+219,(vlTOPp->mkAscon_engine__DOT__y___05Fh19304),64);
        tracep->fullWData(oldp+221,(vlTOPp->mkAscon_engine__DOT__intialization_output___05Fh6775),320);
        tracep->fullWData(oldp+231,(vlTOPp->mkAscon_engine__DOT__lv_updated_asso_data___05Fh12195),320);
        tracep->fullWData(oldp+241,(vlTOPp->mkAscon_engine__DOT__packed_associated_data___05Fh11523),320);
        tracep->fullWData(oldp+251,(vlTOPp->mkAscon_engine__DOT__padded_key___05Fh6735),320);
        tracep->fullWData(oldp+261,(vlTOPp->mkAscon_engine__DOT__padded_key_state___05Fh16617),320);
        tracep->fullWData(oldp+271,(vlTOPp->mkAscon_engine__DOT__pre_finalized_state___05Fh17084),320);
        tracep->fullWData(oldp+281,(vlTOPp->mkAscon_engine__DOT__rg_state_0_2_CONCAT_rg_state_1_4_6_XOR_rg_inte_ETC___05F_d235),128);
        tracep->fullQData(oldp+285,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_iv_constant_1_ELSE_rg_sta_ETC___05F_d33),64);
        tracep->fullQData(oldp+287,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_127_ETC___05F_d15),64);
        tracep->fullQData(oldp+289,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d23),64);
        tracep->fullQData(oldp+291,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_0_2_BITS_63___05FETC___05F_d27),64);
        tracep->fullQData(oldp+293,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_127_T_ETC___05F_d19),64);
        tracep->fullQData(oldp+295,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d103),64);
        tracep->fullQData(oldp+297,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d109),64);
        tracep->fullQData(oldp+299,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d11),64);
        tracep->fullQData(oldp+301,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d117),64);
        tracep->fullQData(oldp+303,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d37),64);
        tracep->fullQData(oldp+305,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d45),64);
        tracep->fullQData(oldp+307,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d62),64);
        tracep->fullQData(oldp+309,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d70),64);
        tracep->fullQData(oldp+311,(vlTOPp->mkAscon_engine__DOT__IF_counter_EQ_0_THEN_rg_interface_3_BITS_63_TO_ETC___05F_d95),64);
        tracep->fullQData(oldp+313,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d77),64);
        tracep->fullQData(oldp+315,(vlTOPp->mkAscon_engine__DOT__INV_IF_counter_EQ_0_THEN_rg_interface_3_BITS_6_ETC___05F_d85),64);
        tracep->fullQData(oldp+317,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___05F_d183),64);
        tracep->fullQData(oldp+319,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___05F_d191),64);
        tracep->fullQData(oldp+321,(vlTOPp->mkAscon_engine__DOT__INV_rg_state_4_0_AND_rg_state_3_8_79_XOR_rg_st_ETC___05F_d269),64);
        tracep->fullQData(oldp+323,(vlTOPp->mkAscon_engine__DOT__din___05Fh12423),64);
        tracep->fullQData(oldp+325,(vlTOPp->mkAscon_engine__DOT__encryption0___05Fh16813),64);
        tracep->fullQData(oldp+327,(vlTOPp->mkAscon_engine__DOT__encryption1___05Fh16814),64);
        tracep->fullQData(oldp+329,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d138),64);
        tracep->fullQData(oldp+331,(vlTOPp->mkAscon_engine__DOT__rg_state_2_2_XOR_SEL_ARR_75_90_105_120_135_150_ETC___05F_d251),64);
        tracep->fullQData(oldp+333,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state___05FETC___05F_d200),64);
        tracep->fullQData(oldp+335,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state___05FETC___05F_d208),64);
        tracep->fullQData(oldp+337,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_0_2_93_XOR_rg_state___05FETC___05F_d272),64);
        tracep->fullQData(oldp+339,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state___05FETC___05F_d145),64);
        tracep->fullQData(oldp+341,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state___05FETC___05F_d153),64);
        tracep->fullQData(oldp+343,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state___05FETC___05F_d221),64);
        tracep->fullQData(oldp+345,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_AND_rg_state_1_4_34_XOR_rg_state___05FETC___05F_d257),64);
        tracep->fullQData(oldp+347,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d167),64);
        tracep->fullQData(oldp+349,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d175),64);
        tracep->fullQData(oldp+351,(vlTOPp->mkAscon_engine__DOT__rg_state_4_0_XOR_rg_state_2_2_XOR_SEL_ARR_75_9_ETC___05F_d266),64);
        tracep->fullQData(oldp+353,(vlTOPp->mkAscon_engine__DOT__x___05Fh10893),64);
        tracep->fullQData(oldp+355,(vlTOPp->mkAscon_engine__DOT__x___05Fh10982),64);
        tracep->fullQData(oldp+357,(vlTOPp->mkAscon_engine__DOT__x___05Fh14222),64);
        tracep->fullQData(oldp+359,(vlTOPp->mkAscon_engine__DOT__x___05Fh14224),64);
        tracep->fullQData(oldp+361,(vlTOPp->mkAscon_engine__DOT__x___05Fh14226),64);
        tracep->fullQData(oldp+363,(vlTOPp->mkAscon_engine__DOT__x___05Fh14228),64);
        tracep->fullQData(oldp+365,(vlTOPp->mkAscon_engine__DOT__x___05Fh14349),64);
        tracep->fullQData(oldp+367,(vlTOPp->mkAscon_engine__DOT__x___05Fh14351),64);
        tracep->fullQData(oldp+369,(vlTOPp->mkAscon_engine__DOT__x___05Fh14353),64);
        tracep->fullQData(oldp+371,(vlTOPp->mkAscon_engine__DOT__x___05Fh14355),64);
        tracep->fullQData(oldp+373,(vlTOPp->mkAscon_engine__DOT__x___05Fh14357),64);
        tracep->fullQData(oldp+375,(vlTOPp->mkAscon_engine__DOT__x___05Fh14359),64);
        tracep->fullQData(oldp+377,(vlTOPp->mkAscon_engine__DOT__x___05Fh14489),64);
        tracep->fullQData(oldp+379,(vlTOPp->mkAscon_engine__DOT__x___05Fh14563),64);
        tracep->fullQData(oldp+381,(vlTOPp->mkAscon_engine__DOT__x___05Fh14565),64);
        tracep->fullQData(oldp+383,(vlTOPp->mkAscon_engine__DOT__x___05Fh14899),64);
        tracep->fullQData(oldp+385,(vlTOPp->mkAscon_engine__DOT__x___05Fh15140),64);
        tracep->fullQData(oldp+387,(vlTOPp->mkAscon_engine__DOT__x___05Fh15381),64);
        tracep->fullQData(oldp+389,(vlTOPp->mkAscon_engine__DOT__x___05Fh15622),64);
        tracep->fullQData(oldp+391,(vlTOPp->mkAscon_engine__DOT__x___05Fh20170),64);
        tracep->fullQData(oldp+393,(vlTOPp->mkAscon_engine__DOT__x___05Fh20172),64);
        tracep->fullQData(oldp+395,(vlTOPp->mkAscon_engine__DOT__x___05Fh20174),64);
        tracep->fullQData(oldp+397,(vlTOPp->mkAscon_engine__DOT__x___05Fh20176),64);
        tracep->fullQData(oldp+399,(vlTOPp->mkAscon_engine__DOT__x___05Fh20178),64);
        tracep->fullQData(oldp+401,(vlTOPp->mkAscon_engine__DOT__x___05Fh20297),64);
        tracep->fullQData(oldp+403,(vlTOPp->mkAscon_engine__DOT__x___05Fh20299),64);
        tracep->fullQData(oldp+405,(vlTOPp->mkAscon_engine__DOT__x___05Fh20301),64);
        tracep->fullQData(oldp+407,(vlTOPp->mkAscon_engine__DOT__x___05Fh20303),64);
        tracep->fullQData(oldp+409,(vlTOPp->mkAscon_engine__DOT__x___05Fh20305),64);
        tracep->fullQData(oldp+411,(vlTOPp->mkAscon_engine__DOT__x___05Fh20307),64);
        tracep->fullQData(oldp+413,(vlTOPp->mkAscon_engine__DOT__x___05Fh20437),64);
        tracep->fullQData(oldp+415,(vlTOPp->mkAscon_engine__DOT__x___05Fh20439),64);
        tracep->fullQData(oldp+417,(vlTOPp->mkAscon_engine__DOT__x___05Fh20441),64);
        tracep->fullQData(oldp+419,(vlTOPp->mkAscon_engine__DOT__x___05Fh20511),64);
        tracep->fullQData(oldp+421,(vlTOPp->mkAscon_engine__DOT__x___05Fh20513),64);
        tracep->fullQData(oldp+423,(vlTOPp->mkAscon_engine__DOT__x___05Fh20515),64);
        tracep->fullQData(oldp+425,(vlTOPp->mkAscon_engine__DOT__x___05Fh20517),64);
        tracep->fullQData(oldp+427,(vlTOPp->mkAscon_engine__DOT__x___05Fh20519),64);
        tracep->fullQData(oldp+429,(vlTOPp->mkAscon_engine__DOT__x___05Fh20521),64);
        tracep->fullQData(oldp+431,(vlTOPp->mkAscon_engine__DOT__x___05Fh20627),64);
        tracep->fullQData(oldp+433,(vlTOPp->mkAscon_engine__DOT__x___05Fh20629),64);
        tracep->fullQData(oldp+435,(vlTOPp->mkAscon_engine__DOT__x___05Fh20631),64);
        tracep->fullQData(oldp+437,(vlTOPp->mkAscon_engine__DOT__x___05Fh20633),64);
        tracep->fullQData(oldp+439,(vlTOPp->mkAscon_engine__DOT__x___05Fh20847),64);
        tracep->fullQData(oldp+441,(vlTOPp->mkAscon_engine__DOT__x___05Fh21088),64);
        tracep->fullQData(oldp+443,(vlTOPp->mkAscon_engine__DOT__x___05Fh21329),64);
        tracep->fullQData(oldp+445,(vlTOPp->mkAscon_engine__DOT__x___05Fh21570),64);
        tracep->fullQData(oldp+447,(vlTOPp->mkAscon_engine__DOT__x___05Fh21811),64);
        tracep->fullQData(oldp+449,(vlTOPp->mkAscon_engine__DOT__x___05Fh21813),64);
        tracep->fullQData(oldp+451,(vlTOPp->mkAscon_engine__DOT__x___05Fh3980),64);
        tracep->fullQData(oldp+453,(vlTOPp->mkAscon_engine__DOT__x___05Fh3982),64);
        tracep->fullQData(oldp+455,(vlTOPp->mkAscon_engine__DOT__x___05Fh3984),64);
        tracep->fullQData(oldp+457,(vlTOPp->mkAscon_engine__DOT__x___05Fh3986),64);
        tracep->fullQData(oldp+459,(vlTOPp->mkAscon_engine__DOT__x___05Fh3988),64);
        tracep->fullQData(oldp+461,(vlTOPp->mkAscon_engine__DOT__x___05Fh3990),64);
        tracep->fullQData(oldp+463,(vlTOPp->mkAscon_engine__DOT__x___05Fh4107),64);
        tracep->fullQData(oldp+465,(vlTOPp->mkAscon_engine__DOT__x___05Fh4109),64);
        tracep->fullQData(oldp+467,(vlTOPp->mkAscon_engine__DOT__x___05Fh4111),64);
        tracep->fullQData(oldp+469,(vlTOPp->mkAscon_engine__DOT__x___05Fh4113),64);
        tracep->fullQData(oldp+471,(vlTOPp->mkAscon_engine__DOT__x___05Fh4115),64);
        tracep->fullQData(oldp+473,(vlTOPp->mkAscon_engine__DOT__x___05Fh4117),64);
        tracep->fullQData(oldp+475,(vlTOPp->mkAscon_engine__DOT__x___05Fh4247),64);
        tracep->fullQData(oldp+477,(vlTOPp->mkAscon_engine__DOT__x___05Fh4249),64);
        tracep->fullQData(oldp+479,(vlTOPp->mkAscon_engine__DOT__x___05Fh4251),64);
        tracep->fullQData(oldp+481,(vlTOPp->mkAscon_engine__DOT__x___05Fh4321),64);
        tracep->fullQData(oldp+483,(vlTOPp->mkAscon_engine__DOT__x___05Fh4323),64);
        tracep->fullQData(oldp+485,(vlTOPp->mkAscon_engine__DOT__x___05Fh4325),64);
        tracep->fullQData(oldp+487,(vlTOPp->mkAscon_engine__DOT__x___05Fh4327),64);
        tracep->fullQData(oldp+489,(vlTOPp->mkAscon_engine__DOT__x___05Fh4329),64);
        tracep->fullQData(oldp+491,(vlTOPp->mkAscon_engine__DOT__x___05Fh4331),64);
        tracep->fullQData(oldp+493,(vlTOPp->mkAscon_engine__DOT__x___05Fh4437),64);
        tracep->fullQData(oldp+495,(vlTOPp->mkAscon_engine__DOT__x___05Fh4439),64);
        tracep->fullQData(oldp+497,(vlTOPp->mkAscon_engine__DOT__x___05Fh4441),64);
        tracep->fullQData(oldp+499,(vlTOPp->mkAscon_engine__DOT__x___05Fh4657),64);
        tracep->fullQData(oldp+501,(vlTOPp->mkAscon_engine__DOT__x___05Fh4898),64);
        tracep->fullQData(oldp+503,(vlTOPp->mkAscon_engine__DOT__x___05Fh5139),64);
        tracep->fullQData(oldp+505,(vlTOPp->mkAscon_engine__DOT__x___05Fh5380),64);
        tracep->fullQData(oldp+507,(vlTOPp->mkAscon_engine__DOT__x___05Fh5621),64);
        tracep->fullQData(oldp+509,(vlTOPp->mkAscon_engine__DOT__y___05Fh14231),64);
        tracep->fullQData(oldp+511,(vlTOPp->mkAscon_engine__DOT__y___05Fh14354),64);
        tracep->fullQData(oldp+513,(vlTOPp->mkAscon_engine__DOT__y___05Fh14362),64);
        tracep->fullQData(oldp+515,(vlTOPp->mkAscon_engine__DOT__y___05Fh14900),64);
        tracep->fullQData(oldp+517,(vlTOPp->mkAscon_engine__DOT__y___05Fh14902),64);
        tracep->fullQData(oldp+519,(vlTOPp->mkAscon_engine__DOT__y___05Fh15141),64);
        tracep->fullQData(oldp+521,(vlTOPp->mkAscon_engine__DOT__y___05Fh15143),64);
        tracep->fullQData(oldp+523,(vlTOPp->mkAscon_engine__DOT__y___05Fh15382),64);
        tracep->fullQData(oldp+525,(vlTOPp->mkAscon_engine__DOT__y___05Fh15384),64);
        tracep->fullQData(oldp+527,(vlTOPp->mkAscon_engine__DOT__y___05Fh15623),64);
        tracep->fullQData(oldp+529,(vlTOPp->mkAscon_engine__DOT__y___05Fh15625),64);
        tracep->fullQData(oldp+531,(vlTOPp->mkAscon_engine__DOT__y___05Fh20179),64);
        tracep->fullQData(oldp+533,(vlTOPp->mkAscon_engine__DOT__y___05Fh20302),64);
        tracep->fullQData(oldp+535,(vlTOPp->mkAscon_engine__DOT__y___05Fh20306),64);
        tracep->fullQData(oldp+537,(vlTOPp->mkAscon_engine__DOT__y___05Fh20310),64);
        tracep->fullQData(oldp+539,(vlTOPp->mkAscon_engine__DOT__y___05Fh20522),64);
        tracep->fullQData(oldp+541,(vlTOPp->mkAscon_engine__DOT__y___05Fh20630),64);
        tracep->fullQData(oldp+543,(vlTOPp->mkAscon_engine__DOT__y___05Fh20848),64);
        tracep->fullQData(oldp+545,(vlTOPp->mkAscon_engine__DOT__y___05Fh20850),64);
        tracep->fullQData(oldp+547,(vlTOPp->mkAscon_engine__DOT__y___05Fh21089),64);
        tracep->fullQData(oldp+549,(vlTOPp->mkAscon_engine__DOT__y___05Fh21091),64);
        tracep->fullQData(oldp+551,(vlTOPp->mkAscon_engine__DOT__y___05Fh21330),64);
        tracep->fullQData(oldp+553,(vlTOPp->mkAscon_engine__DOT__y___05Fh21332),64);
        tracep->fullQData(oldp+555,(vlTOPp->mkAscon_engine__DOT__y___05Fh21571),64);
        tracep->fullQData(oldp+557,(vlTOPp->mkAscon_engine__DOT__y___05Fh21573),64);
        tracep->fullQData(oldp+559,(vlTOPp->mkAscon_engine__DOT__y___05Fh21812),64);
        tracep->fullQData(oldp+561,(vlTOPp->mkAscon_engine__DOT__y___05Fh21814),64);
        tracep->fullQData(oldp+563,(vlTOPp->mkAscon_engine__DOT__y___05Fh3985),64);
        tracep->fullQData(oldp+565,(vlTOPp->mkAscon_engine__DOT__y___05Fh3989),64);
        tracep->fullQData(oldp+567,(vlTOPp->mkAscon_engine__DOT__y___05Fh4112),64);
        tracep->fullQData(oldp+569,(vlTOPp->mkAscon_engine__DOT__y___05Fh4116),64);
        tracep->fullQData(oldp+571,(vlTOPp->mkAscon_engine__DOT__y___05Fh4120),64);
        tracep->fullQData(oldp+573,(vlTOPp->mkAscon_engine__DOT__y___05Fh4332),64);
        tracep->fullQData(oldp+575,(vlTOPp->mkAscon_engine__DOT__y___05Fh4658),64);
        tracep->fullQData(oldp+577,(vlTOPp->mkAscon_engine__DOT__y___05Fh4660),64);
        tracep->fullQData(oldp+579,(vlTOPp->mkAscon_engine__DOT__y___05Fh4899),64);
        tracep->fullQData(oldp+581,(vlTOPp->mkAscon_engine__DOT__y___05Fh4901),64);
        tracep->fullQData(oldp+583,(vlTOPp->mkAscon_engine__DOT__y___05Fh5140),64);
        tracep->fullQData(oldp+585,(vlTOPp->mkAscon_engine__DOT__y___05Fh5142),64);
        tracep->fullQData(oldp+587,(vlTOPp->mkAscon_engine__DOT__y___05Fh5381),64);
        tracep->fullQData(oldp+589,(vlTOPp->mkAscon_engine__DOT__y___05Fh5383),64);
        tracep->fullQData(oldp+591,(vlTOPp->mkAscon_engine__DOT__y___05Fh5622),64);
        tracep->fullQData(oldp+593,(vlTOPp->mkAscon_engine__DOT__y___05Fh5624),64);
        tracep->fullCData(oldp+595,(vlTOPp->mkAscon_engine__DOT__x___05Fh13372),4);
        tracep->fullCData(oldp+596,(vlTOPp->mkAscon_engine__DOT__x___05Fh19320),4);
        tracep->fullCData(oldp+597,(vlTOPp->mkAscon_engine__DOT__x___05Fh22665),4);
        tracep->fullBit(oldp+598,(vlTOPp->mkAscon_engine__DOT__counter_ULT_12___05F_d4));
    }
}
